import type { LevelDef } from "./types";

/**
 * Folio XVII — appendix. Ten patrols in **3 + 4 + 3**: macro verb is **margin clamp** (ceiling
 * and floor bites shrink the safe band) then **double-spine braid** (floor runway + upper ribbon
 * with shaft links), then a **closing squeeze** before the seal. Still no eleventh drone—pressure
 * is *vertical clearance* and *which spine is live*, not headcount.
 */
export function createFolioAppendixLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 7400;

  return {
    id: "folio_xvii_appendix",
    name: "Appendix — Folio XVII",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      /* Marginalia — ceiling bites + floor tax */
      {
        kind: "hazard",
        x: 60,
        y: 220,
        w: 180,
        h: 200,
        dps: 2.35,
      },
      { kind: "solid", x: 260, y: 388, w: 100, h: 16 },
      {
        kind: "hazard",
        x: 400,
        y: 200,
        w: 220,
        h: 220,
        dps: 2.45,
      },
      { kind: "solid", x: 640, y: 364, w: 80, h: 14 },
      {
        kind: "hazard",
        x: 760,
        y: floorY - 40,
        w: 200,
        h: 40,
        dps: 2.5,
      },

      /* Volume A — three floor drones under margin read */
      { kind: "solid", x: 480, y: 332, w: 1400, h: 26 },
      {
        kind: "hazard",
        x: 620,
        y: 240,
        w: 40,
        h: 180,
        dps: 2.52,
      },
      {
        kind: "hazard",
        x: 1180,
        y: 210,
        w: 48,
        h: 210,
        dps: 2.55,
      },
      {
        kind: "patrol",
        id: "appendix_drone_a",
        x: 640,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -96,
        patrolLeft: 500,
        patrolRight: 1120,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "appendix_drone_b",
        x: 1040,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 88,
        patrolLeft: 540,
        patrolRight: 1280,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "appendix_drone_c",
        x: 1480,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -74,
        patrolLeft: 600,
        patrolRight: 1820,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 1880,
        y: floorY - 34,
        w: 110,
        h: 34,
        dps: 2.72,
      },
      { kind: "solid", x: 1860, y: 358, w: 52, h: 14 },
      { kind: "solid", x: 1960, y: 358, w: 52, h: 14 },

      /* Volume B — double spine: ribbon + floor wells */
      {
        kind: "hazard",
        x: 2040,
        y: floorY - 30,
        w: 280,
        h: 30,
        dps: 2.68,
      },
      {
        kind: "hazard",
        x: 2360,
        y: floorY - 30,
        w: 260,
        h: 30,
        dps: 2.68,
      },
      { kind: "solid", x: 2060, y: 268, w: 360, h: 18 },
      {
        kind: "patrol",
        id: "appendix_drone_d",
        x: 2200,
        y: 240,
        w: 28,
        h: 28,
        vx: 104,
        patrolLeft: 2080,
        patrolRight: 2380,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      { kind: "solid", x: 2440, y: 268, w: 320, h: 18 },
      {
        kind: "patrol",
        id: "appendix_drone_e",
        x: 2580,
        y: 240,
        w: 28,
        h: 28,
        vx: -86,
        patrolLeft: 2460,
        patrolRight: 2720,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      { kind: "solid", x: 2780, y: floorY - 12, w: 440, h: 12 },
      {
        kind: "patrol",
        id: "appendix_drone_f",
        x: 2920,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 72,
        patrolLeft: 2820,
        patrolRight: 3180,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      { kind: "solid", x: 2860, y: 268, w: 300, h: 18 },
      {
        kind: "patrol",
        id: "appendix_drone_g",
        x: 3000,
        y: 240,
        w: 28,
        h: 28,
        vx: -92,
        patrolLeft: 2880,
        patrolRight: 3120,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "hazard",
        x: 3240,
        y: floorY - 32,
        w: 240,
        h: 32,
        dps: 2.64,
      },
      { kind: "solid", x: 3220, y: 178, w: 200, h: 16 },
      {
        kind: "checkpoint",
        id: "appendix_mid",
        x: 3320,
        y: 168,
        w: 48,
        h: 76,
      },
      { kind: "solid", x: 3380, y: 288, w: 480, h: 20 },

      /* Volume C — closing squeeze + three floor drones */
      {
        kind: "hazard",
        x: 3520,
        y: 260,
        w: 360,
        h: 160,
        dps: 2.48,
      },
      { kind: "solid", x: 3560, y: 332, w: 800, h: 24 },
      {
        kind: "hazard",
        x: 3680,
        y: floorY - 46,
        w: 120,
        h: 46,
        dps: 2.6,
      },
      {
        kind: "hazard",
        x: 4040,
        y: floorY - 46,
        w: 120,
        h: 46,
        dps: 2.6,
      },
      {
        kind: "patrol",
        id: "appendix_drone_h",
        x: 3720,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -98,
        patrolLeft: 3580,
        patrolRight: 3960,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "appendix_drone_i",
        x: 4040,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 84,
        patrolLeft: 3640,
        patrolRight: 4280,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "appendix_drone_j",
        x: 4180,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -70,
        patrolLeft: 3720,
        patrolRight: 4320,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 4380, y: 252, w: 180, h: 18 },
      {
        kind: "hazard",
        x: 4440,
        y: floorY - 52,
        w: 280,
        h: 52,
        dps: 2.58,
      },
      { kind: "solid", x: 4620, y: 304, w: 140, h: 18 },

      {
        kind: "boss_gate",
        x: 4780,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Appendix is what survives editing—margins, braid, squeeze.\nBinder stitches the spines the steward could not shelve alone.",
      },

      { kind: "solid", x: 4848, y: 146, w: 1980, h: 28 },
      { kind: "solid", x: 4902, y: 344, w: 74, h: 144 },
      { kind: "solid", x: 6300, y: 344, w: 74, h: 144 },
      {
        kind: "hazard",
        x: 4980,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.4,
      },
      { kind: "solid", x: 5056, y: floorY - 12, w: 66, h: 12 },
      {
        kind: "hazard",
        x: 5122,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.4,
      },
      { kind: "solid", x: 5198, y: 268, w: 420, h: 22 },
      {
        kind: "hazard",
        x: 5660,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 5728, y: floorY - 11, w: 56, h: 11 },
      {
        kind: "hazard",
        x: 5784,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 5852, y: 384, w: 480, h: 22 },
      { kind: "solid", x: 6160, y: 316, w: 340, h: 20 },
      {
        kind: "exit",
        x: 6560,
        y: 194,
        w: 48,
        h: 86,
      },
    ],
  };
}
