import type { LevelDef } from "./types";

/**
 * Folio XVI — index. Ten patrols in **3 + 3 + 4**: macro verb is **stacks + mezzanine +
 * tabs** — vertical hazard spines force jump/over reads, a **catwalk band** crosses hazard
 * wells, then **shelf-tab** ledges finish the argument. No eleventh drone; difficulty is
 * **lane height** and **cross-reference timing**, not headcount.
 */
export function createFolioIndexLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 7200;

  return {
    id: "folio_xvi_index",
    name: "Index — Folio XVI",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      /* Shelving read — shallow alternating tax before stacks */
      {
        kind: "hazard",
        x: 48,
        y: floorY - 36,
        w: 200,
        h: 36,
        dps: 2.2,
      },
      { kind: "solid", x: 268, y: 404, w: 88, h: 16 },
      {
        kind: "hazard",
        x: 388,
        y: floorY - 44,
        w: 240,
        h: 44,
        dps: 2.38,
      },
      { kind: "solid", x: 648, y: 364, w: 72, h: 14 },

      /* Volume A — three floor drones between spine gaps */
      { kind: "solid", x: 520, y: 332, w: 1280, h: 26 },
      {
        kind: "hazard",
        x: 620,
        y: 360,
        w: 28,
        h: 120,
        dps: 2.5,
      },
      {
        kind: "hazard",
        x: 1120,
        y: 348,
        w: 32,
        h: 132,
        dps: 2.55,
      },
      {
        kind: "hazard",
        x: 1580,
        y: 356,
        w: 30,
        h: 124,
        dps: 2.52,
      },
      {
        kind: "patrol",
        id: "index_drone_a",
        x: 720,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -102,
        patrolLeft: 540,
        patrolRight: 1180,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "index_drone_b",
        x: 1080,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 94,
        patrolLeft: 580,
        patrolRight: 1240,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "index_drone_c",
        x: 1560,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -80,
        patrolLeft: 640,
        patrolRight: 1760,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 1820,
        y: floorY - 32,
        w: 100,
        h: 32,
        dps: 2.7,
      },
      { kind: "solid", x: 1800, y: 358, w: 48, h: 14 },
      { kind: "solid", x: 1908, y: 358, w: 48, h: 14 },

      /* Volume B — mezzanine cross-reference + one floor runner */
      {
        kind: "hazard",
        x: 1980,
        y: floorY - 28,
        w: 360,
        h: 28,
        dps: 2.65,
      },
      {
        kind: "hazard",
        x: 2380,
        y: floorY - 28,
        w: 320,
        h: 28,
        dps: 2.65,
      },
      {
        kind: "hazard",
        x: 2740,
        y: floorY - 28,
        w: 340,
        h: 28,
        dps: 2.65,
      },
      { kind: "solid", x: 2000, y: 278, w: 340, h: 20 },
      {
        kind: "patrol",
        id: "index_drone_d",
        x: 2140,
        y: 250,
        w: 28,
        h: 28,
        vx: 108,
        patrolLeft: 2020,
        patrolRight: 2300,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      { kind: "solid", x: 2380, y: 278, w: 300, h: 20 },
      {
        kind: "patrol",
        id: "index_drone_e",
        x: 2520,
        y: 250,
        w: 28,
        h: 28,
        vx: -90,
        patrolLeft: 2400,
        patrolRight: 2640,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      { kind: "solid", x: 2720, y: 278, w: 360, h: 20 },
      { kind: "solid", x: 3140, y: floorY - 12, w: 520, h: 12 },
      {
        kind: "patrol",
        id: "index_drone_f",
        x: 3340,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 76,
        patrolLeft: 3180,
        patrolRight: 3720,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "hazard",
        x: 3120,
        y: floorY - 28,
        w: 280,
        h: 28,
        dps: 2.62,
      },

      { kind: "solid", x: 3480, y: 268, w: 280, h: 18 },
      {
        kind: "hazard",
        x: 3520,
        y: floorY - 40,
        w: 200,
        h: 40,
        dps: 2.5,
      },

      { kind: "solid", x: 3380, y: 188, w: 220, h: 16 },
      {
        kind: "checkpoint",
        id: "index_mid",
        x: 3480,
        y: 178,
        w: 48,
        h: 76,
      },

      /* Volume C — tab shelves, four drones */
      { kind: "solid", x: 3640, y: 312, w: 720, h: 24 },
      {
        kind: "hazard",
        x: 3720,
        y: 328,
        w: 36,
        h: 152,
        dps: 2.48,
      },
      {
        kind: "hazard",
        x: 4120,
        y: 320,
        w: 34,
        h: 160,
        dps: 2.5,
      },
      {
        kind: "patrol",
        id: "index_drone_g",
        x: 3780,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -100,
        patrolLeft: 3660,
        patrolRight: 4080,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "index_drone_h",
        x: 4040,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 86,
        patrolLeft: 3700,
        patrolRight: 4280,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "index_drone_i",
        x: 4200,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -72,
        patrolLeft: 3760,
        patrolRight: 4320,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "index_drone_j",
        x: 3920,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 68,
        patrolLeft: 3820,
        patrolRight: 4180,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 4320, y: 248, w: 200, h: 18 },
      {
        kind: "hazard",
        x: 4380,
        y: floorY - 50,
        w: 260,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 4540, y: 292, w: 120, h: 18 },

      {
        kind: "boss_gate",
        x: 4660,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Index is cross-reference—floor, mezzanine, tab.\nSteward shelves the spine you proved in postscript.",
      },

      { kind: "solid", x: 4728, y: 146, w: 1980, h: 28 },
      { kind: "solid", x: 4782, y: 344, w: 74, h: 144 },
      { kind: "solid", x: 6180, y: 344, w: 74, h: 144 },
      {
        kind: "hazard",
        x: 4860,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.4,
      },
      { kind: "solid", x: 4936, y: floorY - 12, w: 66, h: 12 },
      {
        kind: "hazard",
        x: 5002,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.4,
      },
      { kind: "solid", x: 5078, y: 268, w: 420, h: 22 },
      {
        kind: "hazard",
        x: 5540,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 5608, y: floorY - 11, w: 56, h: 11 },
      {
        kind: "hazard",
        x: 5664,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 5732, y: 384, w: 480, h: 22 },
      { kind: "solid", x: 6040, y: 316, w: 340, h: 20 },
      {
        kind: "exit",
        x: 6440,
        y: 194,
        w: 48,
        h: 86,
      },
    ],
  };
}
