import type { LevelDef } from "./types";

/**
 * Folio XXI — afterline. Ten patrols in **3 + 4 + 3**: macro verb is **attest corridor** (tall side
 * hazards pinching a center line), **hopscotch relay** (small islands over pits on one runway), then
 * **closing tread** (dense floor teeth before the seal). Ten drones—signature line energy, not a new headcount.
 */
export function createFolioAfterlineLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 8880;

  return {
    id: "folio_xxi_afterline",
    name: "Afterline — Folio XXI",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      {
        kind: "hazard",
        x: 40,
        y: floorY - 34,
        w: 170,
        h: 34,
        dps: 2.34,
      },
      { kind: "solid", x: 230, y: 402, w: 84, h: 14 },

      /* Volume A — attest corridor */
      {
        kind: "hazard",
        x: 420,
        y: 260,
        w: 48,
        h: 200,
        dps: 2.52,
      },
      {
        kind: "hazard",
        x: 1780,
        y: 260,
        w: 48,
        h: 200,
        dps: 2.52,
      },
      { kind: "solid", x: 480, y: 332, w: 1320, h: 26 },
      {
        kind: "patrol",
        id: "afterline_drone_a",
        x: 720,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -106,
        patrolLeft: 500,
        patrolRight: 1280,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "afterline_drone_b",
        x: 1180,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 98,
        patrolLeft: 540,
        patrolRight: 1620,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "afterline_drone_c",
        x: 1540,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -84,
        patrolLeft: 580,
        patrolRight: 1760,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 1820,
        y: floorY - 36,
        w: 100,
        h: 36,
        dps: 2.72,
      },
      { kind: "solid", x: 1800, y: 358, w: 52, h: 14 },
      { kind: "solid", x: 1908, y: 358, w: 52, h: 14 },

      /* Volume B — hopscotch relay */
      {
        kind: "hazard",
        x: 1940,
        y: floorY - 32,
        w: 360,
        h: 32,
        dps: 2.68,
      },
      { kind: "solid", x: 2060, y: 364, w: 88, h: 14 },
      {
        kind: "hazard",
        x: 2320,
        y: floorY - 32,
        w: 340,
        h: 32,
        dps: 2.68,
      },
      { kind: "solid", x: 2440, y: 364, w: 88, h: 14 },
      {
        kind: "hazard",
        x: 2680,
        y: floorY - 32,
        w: 380,
        h: 32,
        dps: 2.68,
      },
      { kind: "solid", x: 2820, y: 364, w: 88, h: 14 },
      { kind: "solid", x: 1960, y: 332, w: 1920, h: 26 },
      {
        kind: "patrol",
        id: "afterline_drone_d",
        x: 2140,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 110,
        patrolLeft: 1980,
        patrolRight: 2520,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "afterline_drone_e",
        x: 2580,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -94,
        patrolLeft: 2280,
        patrolRight: 2920,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "afterline_drone_f",
        x: 3020,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 80,
        patrolLeft: 2680,
        patrolRight: 3360,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "afterline_drone_g",
        x: 3480,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -102,
        patrolLeft: 2920,
        patrolRight: 3780,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 3920,
        y: floorY - 34,
        w: 200,
        h: 34,
        dps: 2.66,
      },
      { kind: "solid", x: 3940, y: 180, w: 260, h: 16 },
      {
        kind: "checkpoint",
        id: "afterline_mid",
        x: 4040,
        y: 170,
        w: 48,
        h: 76,
      },

      /* Volume C — closing tread */
      { kind: "solid", x: 4120, y: 332, w: 1120, h: 26 },
      {
        kind: "hazard",
        x: 4200,
        y: floorY - 44,
        w: 100,
        h: 44,
        dps: 2.56,
      },
      {
        kind: "hazard",
        x: 4440,
        y: floorY - 44,
        w: 100,
        h: 44,
        dps: 2.56,
      },
      {
        kind: "hazard",
        x: 4680,
        y: floorY - 44,
        w: 100,
        h: 44,
        dps: 2.56,
      },
      {
        kind: "hazard",
        x: 4920,
        y: floorY - 44,
        w: 100,
        h: 44,
        dps: 2.56,
      },
      {
        kind: "patrol",
        id: "afterline_drone_h",
        x: 4320,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -92,
        patrolLeft: 4140,
        patrolRight: 4680,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "afterline_drone_i",
        x: 4680,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 88,
        patrolLeft: 4240,
        patrolRight: 5000,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "afterline_drone_j",
        x: 5040,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -74,
        patrolLeft: 4480,
        patrolRight: 5180,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 5280, y: 260, w: 200, h: 18 },
      {
        kind: "hazard",
        x: 5360,
        y: floorY - 52,
        w: 300,
        h: 52,
        dps: 2.58,
      },
      { kind: "solid", x: 5560, y: 308, w: 140, h: 18 },

      {
        kind: "boss_gate",
        x: 6720,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Afterline is the attest—corridor, hopscotch, tread.\nNotary embosses what codex bound and chronicler filed.",
      },

      { kind: "solid", x: 6788, y: 146, w: 1980, h: 28 },
      { kind: "solid", x: 6842, y: 344, w: 74, h: 144 },
      { kind: "solid", x: 8240, y: 344, w: 74, h: 144 },
      {
        kind: "hazard",
        x: 6920,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.4,
      },
      { kind: "solid", x: 6996, y: floorY - 12, w: 66, h: 12 },
      {
        kind: "hazard",
        x: 7062,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.4,
      },
      { kind: "solid", x: 7138, y: 268, w: 420, h: 22 },
      {
        kind: "hazard",
        x: 7600,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 7668, y: floorY - 11, w: 56, h: 11 },
      {
        kind: "hazard",
        x: 7724,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 7792, y: 384, w: 480, h: 22 },
      { kind: "solid", x: 8100, y: 316, w: 340, h: 20 },
      {
        kind: "exit",
        x: 8520,
        y: 194,
        w: 48,
        h: 86,
      },
    ],
  };
}
