import type { LevelDef } from "./types";

/**
 * Folio XIV — afterword. Still **ten** patrol bodies: pressure is **lateral** (zigzag reads,
 * dual islands with a hazard gulf) — a different verb than Coda’s trench / stepping line.
 */
export function createFolioAfterwordLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 6680;

  return {
    id: "folio_xiv_afterword",
    name: "Afterword — Folio XIV",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      { kind: "solid", x: 12, y: 434, w: 114, h: 18 },
      /* Zigzag ink — wrong lane tax */
      {
        kind: "hazard",
        x: 80,
        y: floorY - 42,
        w: 200,
        h: 42,
        dps: 2.36,
      },
      { kind: "solid", x: 300, y: 368, w: 140, h: 18 },
      {
        kind: "hazard",
        x: 420,
        y: floorY - 50,
        w: 220,
        h: 50,
        dps: 2.5,
      },
      { kind: "solid", x: 640, y: 318, w: 120, h: 18 },
      {
        kind: "hazard",
        x: 760,
        y: floorY - 46,
        w: 260,
        h: 46,
        dps: 2.46,
      },
      { kind: "solid", x: 1020, y: 398, w: 50, h: 82 },

      /* Island A — five drones */
      { kind: "solid", x: 1080, y: 332, w: 680, h: 26 },
      {
        kind: "patrol",
        id: "afterword_drone_a",
        x: 1280,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -116,
        patrolLeft: 1110,
        patrolRight: 1720,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "afterword_drone_b",
        x: 1620,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 106,
        patrolLeft: 1130,
        patrolRight: 1680,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "afterword_drone_c",
        x: 1420,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -92,
        patrolLeft: 1160,
        patrolRight: 1640,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "afterword_drone_d",
        x: 1180,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 84,
        patrolLeft: 1180,
        patrolRight: 1600,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "afterword_drone_e",
        x: 1540,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -76,
        patrolLeft: 1220,
        patrolRight: 1560,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      /* Gulf — commit or pay */
      {
        kind: "hazard",
        x: 1760,
        y: floorY - 32,
        w: 260,
        h: 32,
        dps: 2.72,
      },
      { kind: "solid", x: 1740, y: 364, w: 48, h: 14 },
      { kind: "solid", x: 2000, y: 364, w: 48, h: 14 },

      /* Island B — five drones */
      { kind: "solid", x: 2080, y: 332, w: 740, h: 26 },
      {
        kind: "patrol",
        id: "afterword_drone_f",
        x: 2320,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 114,
        patrolLeft: 2120,
        patrolRight: 2760,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "afterword_drone_g",
        x: 2680,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -102,
        patrolLeft: 2140,
        patrolRight: 2720,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "afterword_drone_h",
        x: 2460,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 78,
        patrolLeft: 2180,
        patrolRight: 2680,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "afterword_drone_i",
        x: 2180,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -68,
        patrolLeft: 2220,
        patrolRight: 2640,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "afterword_drone_j",
        x: 2580,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 56,
        patrolLeft: 2260,
        patrolRight: 2600,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 2880, y: 250, w: 208, h: 18 },
      {
        kind: "hazard",
        x: 2940,
        y: floorY - 56,
        w: 270,
        h: 56,
        dps: 2.58,
      },
      { kind: "solid", x: 3120, y: 190, w: 300, h: 18 },

      {
        kind: "checkpoint",
        id: "afterword_mid",
        x: 3200,
        y: 180,
        w: 48,
        h: 76,
      },

      { kind: "solid", x: 3340, y: 294, w: 420, h: 22 },
      {
        kind: "hazard",
        x: 3460,
        y: floorY - 50,
        w: 220,
        h: 50,
        dps: 2.5,
      },
      { kind: "solid", x: 3680, y: 234, w: 188, h: 16 },
      {
        kind: "hazard",
        x: 3820,
        y: floorY - 46,
        w: 170,
        h: 46,
        dps: 2.48,
      },

      {
        kind: "boss_gate",
        x: 4180,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Afterword is where the story argues with itself.\nScribe won’t bind the volume until you own every contradiction.",
      },

      { kind: "solid", x: 4248, y: 148, w: 1920, h: 28 },
      { kind: "solid", x: 4302, y: 346, w: 72, h: 140 },
      { kind: "solid", x: 6042, y: 346, w: 72, h: 140 },
      {
        kind: "hazard",
        x: 4380,
        y: floorY - 50,
        w: 74,
        h: 50,
        dps: 2.38,
      },
      { kind: "solid", x: 4454, y: floorY - 12, w: 64, h: 12 },
      {
        kind: "hazard",
        x: 4518,
        y: floorY - 50,
        w: 74,
        h: 50,
        dps: 2.38,
      },
      { kind: "solid", x: 4592, y: 270, w: 400, h: 22 },
      {
        kind: "hazard",
        x: 5020,
        y: floorY - 48,
        w: 66,
        h: 48,
        dps: 2.56,
      },
      { kind: "solid", x: 5086, y: floorY - 11, w: 54, h: 11 },
      {
        kind: "hazard",
        x: 5140,
        y: floorY - 48,
        w: 66,
        h: 48,
        dps: 2.56,
      },
      { kind: "solid", x: 5206, y: 386, w: 460, h: 22 },
      { kind: "solid", x: 5500, y: 318, w: 320, h: 20 },
      {
        kind: "exit",
        x: 5900,
        y: 196,
        w: 48,
        h: 86,
      },
    ],
  };
}
