import type { LevelDef } from "./types";

/**
 * Folio XX — codex. Ten patrols in **3 + 4 + 3**: macro verb is **spine + facing pages** (center
 * hazard spine splits left/right lanes), **thread bridges** (short spans over pits), then a
 * **chronicler strip** before the seal. Still ten drones—this chapter is *binding*, not headcount.
 */
export function createFolioCodexLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 8580;

  return {
    id: "folio_xx_codex",
    name: "Codex — Folio XX",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      /* Opening — shallow spine tease */
      {
        kind: "hazard",
        x: 48,
        y: floorY - 36,
        w: 180,
        h: 36,
        dps: 2.32,
      },
      { kind: "solid", x: 248, y: 404, w: 92, h: 16 },

      /* Volume A — facing pages: spine splits the desk */
      { kind: "solid", x: 420, y: 332, w: 720, h: 26 },
      {
        kind: "hazard",
        x: 1120,
        y: 240,
        w: 48,
        h: 200,
        dps: 2.55,
      },
      { kind: "solid", x: 1180, y: 332, w: 760, h: 26 },
      {
        kind: "patrol",
        id: "codex_drone_a",
        x: 680,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -102,
        patrolLeft: 440,
        patrolRight: 1080,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "codex_drone_b",
        x: 1480,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 94,
        patrolLeft: 1200,
        patrolRight: 1880,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "codex_drone_c",
        x: 1080,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -118,
        patrolLeft: 460,
        patrolRight: 1900,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 1960,
        y: floorY - 34,
        w: 110,
        h: 34,
        dps: 2.72,
      },
      { kind: "solid", x: 1940, y: 358, w: 52, h: 14 },
      { kind: "solid", x: 2048, y: 358, w: 52, h: 14 },

      /* Volume B — thread bridges over pits */
      {
        kind: "hazard",
        x: 2100,
        y: floorY - 30,
        w: 320,
        h: 30,
        dps: 2.68,
      },
      { kind: "solid", x: 2220, y: 364, w: 100, h: 14 },
      {
        kind: "hazard",
        x: 2460,
        y: floorY - 30,
        w: 300,
        h: 30,
        dps: 2.68,
      },
      { kind: "solid", x: 2560, y: 364, w: 100, h: 14 },
      {
        kind: "hazard",
        x: 2800,
        y: floorY - 30,
        w: 340,
        h: 30,
        dps: 2.68,
      },
      { kind: "solid", x: 2920, y: 364, w: 100, h: 14 },
      { kind: "solid", x: 2120, y: 332, w: 1680, h: 26 },
      {
        kind: "patrol",
        id: "codex_drone_d",
        x: 2280,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 108,
        patrolLeft: 2140,
        patrolRight: 2680,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "codex_drone_e",
        x: 2720,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -92,
        patrolLeft: 2480,
        patrolRight: 3120,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "codex_drone_f",
        x: 3180,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 78,
        patrolLeft: 2760,
        patrolRight: 3520,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "codex_drone_g",
        x: 3520,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -104,
        patrolLeft: 3000,
        patrolRight: 3720,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 3820,
        y: floorY - 32,
        w: 200,
        h: 32,
        dps: 2.65,
      },
      { kind: "solid", x: 3840, y: 182, w: 240, h: 16 },
      {
        kind: "checkpoint",
        id: "codex_mid",
        x: 3920,
        y: 172,
        w: 48,
        h: 76,
      },

      /* Volume C — chronicler strip */
      { kind: "solid", x: 4000, y: 332, w: 1040, h: 26 },
      {
        kind: "hazard",
        x: 4080,
        y: 300,
        w: 100,
        h: 170,
        dps: 2.48,
      },
      {
        kind: "hazard",
        x: 4860,
        y: 300,
        w: 100,
        h: 170,
        dps: 2.48,
      },
      {
        kind: "hazard",
        x: 4200,
        y: floorY - 42,
        w: 120,
        h: 42,
        dps: 2.58,
      },
      {
        kind: "hazard",
        x: 4680,
        y: floorY - 42,
        w: 120,
        h: 42,
        dps: 2.58,
      },
      {
        kind: "patrol",
        id: "codex_drone_h",
        x: 4240,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -88,
        patrolLeft: 4020,
        patrolRight: 4520,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "codex_drone_i",
        x: 4580,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 96,
        patrolLeft: 4120,
        patrolRight: 4880,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "codex_drone_j",
        x: 4880,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -72,
        patrolLeft: 4320,
        patrolRight: 5000,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 5080, y: 256, w: 200, h: 18 },
      {
        kind: "hazard",
        x: 5160,
        y: floorY - 52,
        w: 280,
        h: 52,
        dps: 2.58,
      },
      { kind: "solid", x: 5340, y: 304, w: 140, h: 18 },

      {
        kind: "boss_gate",
        x: 6420,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Codex is the bound witness—spine, thread, strip.\nChronicler archives what epilogue proved and witness signed.",
      },

      { kind: "solid", x: 6488, y: 146, w: 1980, h: 28 },
      { kind: "solid", x: 6542, y: 344, w: 74, h: 144 },
      { kind: "solid", x: 7940, y: 344, w: 74, h: 144 },
      {
        kind: "hazard",
        x: 6620,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.4,
      },
      { kind: "solid", x: 6696, y: floorY - 12, w: 66, h: 12 },
      {
        kind: "hazard",
        x: 6762,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.4,
      },
      { kind: "solid", x: 6838, y: 268, w: 420, h: 22 },
      {
        kind: "hazard",
        x: 7300,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 7368, y: floorY - 11, w: 56, h: 11 },
      {
        kind: "hazard",
        x: 7424,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 7492, y: 384, w: 480, h: 22 },
      { kind: "solid", x: 7800, y: 316, w: 340, h: 20 },
      {
        kind: "exit",
        x: 8220,
        y: 194,
        w: 48,
        h: 86,
      },
    ],
  };
}
