import type { LevelDef } from "./types";

/**
 * Folio XII — terminus. Unlocks after zenith; exit sealed until the adjudicator falls.
 */
export function createFolioTerminusLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 6120;

  return {
    id: "folio_xii_terminus",
    name: "Terminus — Folio XII",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      { kind: "solid", x: 16, y: 430, w: 124, h: 18 },
      { kind: "solid", x: 180, y: 370, w: 176, h: 18 },
      {
        kind: "hazard",
        x: 130,
        y: floorY - 54,
        w: 300,
        h: 54,
        dps: 2.3,
      },
      { kind: "solid", x: 360, y: 310, w: 134, h: 17 },
      {
        kind: "hazard",
        x: 520,
        y: floorY - 48,
        w: 360,
        h: 48,
        dps: 2.44,
      },
      { kind: "solid", x: 500, y: 394, w: 52, h: 86 },

      /* Ten drones */
      { kind: "solid", x: 500, y: 332, w: 1420, h: 26 },
      {
        kind: "patrol",
        id: "terminus_drone_a",
        x: 760,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -120,
        patrolLeft: 530,
        patrolRight: 1860,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "terminus_drone_b",
        x: 1540,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 110,
        patrolLeft: 550,
        patrolRight: 1820,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "terminus_drone_c",
        x: 1280,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -96,
        patrolLeft: 590,
        patrolRight: 1760,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "terminus_drone_d",
        x: 680,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 88,
        patrolLeft: 610,
        patrolRight: 1700,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "terminus_drone_e",
        x: 1420,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -82,
        patrolLeft: 650,
        patrolRight: 1660,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "terminus_drone_f",
        x: 880,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 74,
        patrolLeft: 670,
        patrolRight: 1620,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "terminus_drone_g",
        x: 1680,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -68,
        patrolLeft: 920,
        patrolRight: 1780,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "terminus_drone_h",
        x: 1040,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 60,
        patrolLeft: 720,
        patrolRight: 1580,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "terminus_drone_i",
        x: 1340,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -54,
        patrolLeft: 980,
        patrolRight: 1720,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "terminus_drone_j",
        x: 1180,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 48,
        patrolLeft: 800,
        patrolRight: 1540,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 1980, y: 254, w: 192, h: 18 },
      {
        kind: "hazard",
        x: 2040,
        y: floorY - 52,
        w: 240,
        h: 52,
        dps: 2.58,
      },
      { kind: "solid", x: 2220, y: 194, w: 280, h: 18 },

      {
        kind: "checkpoint",
        id: "terminus_mid",
        x: 2300,
        y: 184,
        w: 48,
        h: 76,
      },

      { kind: "solid", x: 2440, y: 298, w: 380, h: 22 },
      {
        kind: "hazard",
        x: 2560,
        y: floorY - 46,
        w: 200,
        h: 46,
        dps: 2.48,
      },
      { kind: "solid", x: 2760, y: 238, w: 172, h: 16 },
      {
        kind: "hazard",
        x: 2900,
        y: floorY - 42,
        w: 150,
        h: 42,
        dps: 2.46,
      },

      {
        kind: "boss_gate",
        x: 3280,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Terminus doesn’t negotiate—it closes.\nAdjudicator signs the last line; you supply the ink.",
      },

      { kind: "solid", x: 3348, y: 152, w: 1720, h: 28 },
      { kind: "solid", x: 3402, y: 350, w: 68, h: 132 },
      { kind: "solid", x: 4946, y: 350, w: 68, h: 132 },
      {
        kind: "hazard",
        x: 3470,
        y: floorY - 46,
        w: 72,
        h: 46,
        dps: 2.36,
      },
      { kind: "solid", x: 3542, y: floorY - 12, w: 60, h: 12 },
      {
        kind: "hazard",
        x: 3602,
        y: floorY - 46,
        w: 72,
        h: 46,
        dps: 2.36,
      },
      { kind: "solid", x: 3674, y: 274, w: 360, h: 22 },
      {
        kind: "hazard",
        x: 4040,
        y: floorY - 44,
        w: 64,
        h: 44,
        dps: 2.52,
      },
      { kind: "solid", x: 4104, y: floorY - 11, w: 52, h: 11 },
      {
        kind: "hazard",
        x: 4156,
        y: floorY - 44,
        w: 64,
        h: 44,
        dps: 2.52,
      },
      { kind: "solid", x: 4220, y: 390, w: 420, h: 22 },
      { kind: "solid", x: 4480, y: 322, w: 280, h: 20 },
      {
        kind: "exit",
        x: 4860,
        y: 200,
        w: 48,
        h: 86,
      },
    ],
  };
}
