import type { LevelDef } from "./types";

/**
 * Folio XIX — epilogue. Ten patrols in **3 + 4 + 3**: macro verb is **void ring** (wings + pit +
 * bridge commit), **relay strip** (long desk with mismatched patrol tempos), then **twilight teeth**
 * (closing zipper before the seal). Still ten bodies—this is *closure*, not escalation.
 */
export function createFolioEpilogueLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 8220;

  return {
    id: "folio_xix_epilogue",
    name: "Epilogue — Folio XIX",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      /* Soft open */
      {
        kind: "hazard",
        x: 40,
        y: floorY - 34,
        w: 160,
        h: 34,
        dps: 2.3,
      },
      { kind: "solid", x: 220, y: 400, w: 88, h: 14 },

      /* Volume A — U-void: wings, pit, bridge */
      { kind: "solid", x: 420, y: 332, w: 1120, h: 26 },
      {
        kind: "hazard",
        x: 1540,
        y: floorY - 42,
        w: 500,
        h: 42,
        dps: 2.72,
      },
      { kind: "solid", x: 1680, y: 356, w: 140, h: 16 },
      { kind: "solid", x: 2060, y: 332, w: 720, h: 26 },
      {
        kind: "patrol",
        id: "epilogue_drone_a",
        x: 720,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -104,
        patrolLeft: 440,
        patrolRight: 1480,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "epilogue_drone_b",
        x: 2360,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 96,
        patrolLeft: 2080,
        patrolRight: 2720,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "epilogue_drone_c",
        x: 1280,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 118,
        patrolLeft: 460,
        patrolRight: 1520,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 2780,
        y: floorY - 36,
        w: 100,
        h: 36,
        dps: 2.7,
      },
      { kind: "solid", x: 2760, y: 358, w: 48, h: 14 },
      { kind: "solid", x: 2868, y: 358, w: 48, h: 14 },

      /* Volume B — relay strip (tempo clash) */
      { kind: "solid", x: 2880, y: 332, w: 1760, h: 26 },
      {
        kind: "patrol",
        id: "epilogue_drone_d",
        x: 3040,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -112,
        patrolLeft: 2920,
        patrolRight: 3480,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "epilogue_drone_e",
        x: 3520,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 72,
        patrolLeft: 3000,
        patrolRight: 3920,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "epilogue_drone_f",
        x: 4000,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -98,
        patrolLeft: 3600,
        patrolRight: 4320,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "epilogue_drone_g",
        x: 4380,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 124,
        patrolLeft: 3840,
        patrolRight: 4580,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 4660,
        y: floorY - 32,
        w: 220,
        h: 32,
        dps: 2.64,
      },
      { kind: "solid", x: 4680, y: 182, w: 220, h: 16 },
      {
        kind: "checkpoint",
        id: "epilogue_mid",
        x: 4760,
        y: 172,
        w: 48,
        h: 76,
      },

      /* Volume C — twilight teeth */
      {
        kind: "hazard",
        x: 4820,
        y: floorY - 40,
        w: 200,
        h: 40,
        dps: 2.52,
      },
      { kind: "solid", x: 5040, y: 392, w: 72, h: 14 },
      {
        kind: "hazard",
        x: 5140,
        y: floorY - 44,
        w: 240,
        h: 44,
        dps: 2.56,
      },
      { kind: "solid", x: 5400, y: 364, w: 96, h: 14 },
      {
        kind: "hazard",
        x: 5520,
        y: floorY - 38,
        w: 180,
        h: 38,
        dps: 2.5,
      },
      { kind: "solid", x: 4980, y: 332, w: 900, h: 26 },
      {
        kind: "patrol",
        id: "epilogue_drone_h",
        x: 5020,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -90,
        patrolLeft: 4880,
        patrolRight: 5360,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "epilogue_drone_i",
        x: 5340,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 82,
        patrolLeft: 5000,
        patrolRight: 5720,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "epilogue_drone_j",
        x: 5580,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -76,
        patrolLeft: 5120,
        patrolRight: 5840,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 5760, y: 260, w: 200, h: 18 },
      {
        kind: "hazard",
        x: 5840,
        y: floorY - 52,
        w: 260,
        h: 52,
        dps: 2.58,
      },
      { kind: "solid", x: 6020, y: 304, w: 120, h: 18 },

      {
        kind: "boss_gate",
        x: 6140,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Epilogue is the last light—void, relay, teeth.\nWitness signs the run the compositor could only ink.",
      },

      { kind: "solid", x: 6208, y: 146, w: 1980, h: 28 },
      { kind: "solid", x: 6262, y: 344, w: 74, h: 144 },
      { kind: "solid", x: 7660, y: 344, w: 74, h: 144 },
      {
        kind: "hazard",
        x: 6340,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.4,
      },
      { kind: "solid", x: 6416, y: floorY - 12, w: 66, h: 12 },
      {
        kind: "hazard",
        x: 6482,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.4,
      },
      { kind: "solid", x: 6558, y: 268, w: 420, h: 22 },
      {
        kind: "hazard",
        x: 7020,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 7088, y: floorY - 11, w: 56, h: 11 },
      {
        kind: "hazard",
        x: 7144,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 7212, y: 384, w: 480, h: 22 },
      { kind: "solid", x: 7520, y: 316, w: 340, h: 20 },
      {
        kind: "exit",
        x: 7940,
        y: 194,
        w: 48,
        h: 86,
      },
    ],
  };
}
