import type { LevelDef } from "./types";

/**
 * Folio XV — postscript. Ten patrol bodies in a **tripartite line** (3+4+3) with **bridge commits**
 * between blocks; opener is a **zipper** read (alternating safe teeth). No eleventh drone —
 * macro verb is *segmented runway rhythm*, not more heads.
 */
export function createFolioPostscriptLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 7020;

  return {
    id: "folio_xv_postscript",
    name: "Postscript — Folio XV",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      /* Zipper — alternate wrong-floor tax */
      {
        kind: "hazard",
        x: 40,
        y: floorY - 38,
        w: 220,
        h: 38,
        dps: 2.4,
      },
      { kind: "solid", x: 280, y: 392, w: 100, h: 16 },
      {
        kind: "hazard",
        x: 380,
        y: floorY - 46,
        w: 260,
        h: 46,
        dps: 2.52,
      },
      { kind: "solid", x: 660, y: 338, w: 96, h: 16 },
      {
        kind: "hazard",
        x: 760,
        y: floorY - 42,
        w: 240,
        h: 42,
        dps: 2.48,
      },
      { kind: "solid", x: 1020, y: 404, w: 52, h: 76 },

      /* Block A — three drones */
      { kind: "solid", x: 1080, y: 332, w: 540, h: 26 },
      {
        kind: "patrol",
        id: "postscript_drone_a",
        x: 1240,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -114,
        patrolLeft: 1110,
        patrolRight: 1580,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "postscript_drone_b",
        x: 1500,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 100,
        patrolLeft: 1130,
        patrolRight: 1540,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "postscript_drone_c",
        x: 1340,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -86,
        patrolLeft: 1160,
        patrolRight: 1500,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 1620,
        y: floorY - 30,
        w: 120,
        h: 30,
        dps: 2.74,
      },
      { kind: "solid", x: 1600, y: 358, w: 52, h: 14 },
      { kind: "solid", x: 1710, y: 358, w: 52, h: 14 },

      /* Block B — four drones */
      { kind: "solid", x: 1800, y: 332, w: 620, h: 26 },
      {
        kind: "patrol",
        id: "postscript_drone_d",
        x: 2020,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 108,
        patrolLeft: 1840,
        patrolRight: 2360,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "postscript_drone_e",
        x: 2320,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -94,
        patrolLeft: 1860,
        patrolRight: 2320,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "postscript_drone_f",
        x: 2140,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 80,
        patrolLeft: 1900,
        patrolRight: 2280,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "postscript_drone_g",
        x: 1960,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -72,
        patrolLeft: 1920,
        patrolRight: 2240,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 2420,
        y: floorY - 30,
        w: 120,
        h: 30,
        dps: 2.74,
      },
      { kind: "solid", x: 2400, y: 358, w: 52, h: 14 },
      { kind: "solid", x: 2510, y: 358, w: 52, h: 14 },

      /* Block C — three drones */
      { kind: "solid", x: 2600, y: 332, w: 540, h: 26 },
      {
        kind: "patrol",
        id: "postscript_drone_h",
        x: 2780,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 102,
        patrolLeft: 2640,
        patrolRight: 3100,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "postscript_drone_i",
        x: 3000,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -88,
        patrolLeft: 2660,
        patrolRight: 3060,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "postscript_drone_j",
        x: 2880,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 64,
        patrolLeft: 2700,
        patrolRight: 3020,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 3180, y: 248, w: 216, h: 18 },
      {
        kind: "hazard",
        x: 3240,
        y: floorY - 58,
        w: 290,
        h: 58,
        dps: 2.6,
      },
      { kind: "solid", x: 3420, y: 188, w: 310, h: 18 },

      {
        kind: "checkpoint",
        id: "postscript_mid",
        x: 3500,
        y: 178,
        w: 48,
        h: 76,
      },

      { kind: "solid", x: 3640, y: 292, w: 440, h: 22 },
      {
        kind: "hazard",
        x: 3760,
        y: floorY - 52,
        w: 230,
        h: 52,
        dps: 2.52,
      },
      { kind: "solid", x: 3980, y: 232, w: 196, h: 16 },
      {
        kind: "hazard",
        x: 4120,
        y: floorY - 48,
        w: 175,
        h: 48,
        dps: 2.5,
      },

      {
        kind: "boss_gate",
        x: 4480,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Postscript is rhythm—stutter, bridge, stutter.\nArchivist files the beat you proved across three desks.",
      },

      { kind: "solid", x: 4548, y: 146, w: 1980, h: 28 },
      { kind: "solid", x: 4602, y: 344, w: 74, h: 144 },
      { kind: "solid", x: 6000, y: 344, w: 74, h: 144 },
      {
        kind: "hazard",
        x: 4680,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.4,
      },
      { kind: "solid", x: 4756, y: floorY - 12, w: 66, h: 12 },
      {
        kind: "hazard",
        x: 4822,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.4,
      },
      { kind: "solid", x: 4898, y: 268, w: 420, h: 22 },
      {
        kind: "hazard",
        x: 5360,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 5428, y: floorY - 11, w: 56, h: 11 },
      {
        kind: "hazard",
        x: 5484,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 5552, y: 384, w: 480, h: 22 },
      { kind: "solid", x: 5860, y: 316, w: 340, h: 20 },
      {
        kind: "exit",
        x: 6260,
        y: 194,
        w: 48,
        h: 86,
      },
    ],
  };
}
