import type { LevelDef } from "./types";

/**
 * Folio XXXVI — chapter (first numbered turn of the narrative). Ten patrols in **3 + 4 + 3**:
 * macro verb is **running head band** (header rule tracking the eye), **folio break** (forced page
 * turn / gap between openings), then **section ladder** (subsection steps into the gate). Still ten
 * drones.
 */
export function createFolioChapterLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 10920;

  return {
    id: "folio_xxxvi_chapter",
    name: "Chapter — Folio XXXVI",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      {
        kind: "hazard",
        x: 22,
        y: floorY - 34,
        w: 136,
        h: 34,
        dps: 2.4,
      },
      { kind: "solid", x: 198, y: 390, w: 92, h: 14 },

      /* Volume A — running head band */
      {
        kind: "hazard",
        x: 400,
        y: 140,
        w: 72,
        h: 320,
        dps: 2.54,
      },
      {
        kind: "hazard",
        x: 500,
        y: floorY - 34,
        w: 720,
        h: 34,
        dps: 2.58,
      },
      {
        kind: "hazard",
        x: 520,
        y: 176,
        w: 640,
        h: 30,
        dps: 2.48,
      },
      {
        kind: "hazard",
        x: 560,
        y: 236,
        w: 560,
        h: 28,
        dps: 2.46,
      },
      {
        kind: "hazard",
        x: 1240,
        y: 188,
        w: 48,
        h: 272,
        dps: 2.52,
      },
      { kind: "solid", x: 580, y: 334, w: 680, h: 26 },
      {
        kind: "patrol",
        id: "chapter_drone_a",
        x: 800,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -88,
        patrolLeft: 480,
        patrolRight: 1280,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "chapter_drone_b",
        x: 1100,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 80,
        patrolLeft: 520,
        patrolRight: 1380,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "chapter_drone_c",
        x: 1480,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -74,
        patrolLeft: 560,
        patrolRight: 1680,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 1740,
        y: floorY - 36,
        w: 180,
        h: 36,
        dps: 2.68,
      },
      { kind: "solid", x: 1720, y: 346, w: 58, h: 14 },
      { kind: "solid", x: 1850, y: 346, w: 58, h: 14 },

      /* Volume B — folio break */
      {
        kind: "hazard",
        x: 1920,
        y: floorY - 32,
        w: 128,
        h: 32,
        dps: 2.54,
      },
      {
        kind: "hazard",
        x: 2100,
        y: 172,
        w: 190,
        h: 28,
        dps: 2.48,
      },
      {
        kind: "hazard",
        x: 2360,
        y: floorY - 30,
        w: 400,
        h: 30,
        dps: 2.58,
      },
      { kind: "solid", x: 2140, y: 330, w: 700, h: 26 },
      {
        kind: "hazard",
        x: 2620,
        y: 226,
        w: 48,
        h: 214,
        dps: 2.5,
      },
      {
        kind: "patrol",
        id: "chapter_drone_d",
        x: 2280,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 92,
        patrolLeft: 1960,
        patrolRight: 2720,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "chapter_drone_e",
        x: 2820,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -82,
        patrolLeft: 2200,
        patrolRight: 3160,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "hazard",
        x: 3000,
        y: floorY - 32,
        w: 470,
        h: 32,
        dps: 2.6,
      },
      { kind: "solid", x: 2920, y: 332, w: 800, h: 26 },
      {
        kind: "patrol",
        id: "chapter_drone_f",
        x: 3380,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 76,
        patrolLeft: 2760,
        patrolRight: 3620,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "hazard",
        x: 3440,
        y: 214,
        w: 52,
        h: 234,
        dps: 2.48,
      },
      {
        kind: "patrol",
        id: "chapter_drone_g",
        x: 3900,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -70,
        patrolLeft: 3080,
        patrolRight: 4180,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 4140,
        y: floorY - 34,
        w: 210,
        h: 34,
        dps: 2.64,
      },
      { kind: "solid", x: 4160, y: 154, w: 330, h: 16 },
      {
        kind: "checkpoint",
        id: "chapter_mid",
        x: 4340,
        y: 146,
        w: 48,
        h: 76,
      },

      /* Volume C — section ladder */
      {
        kind: "hazard",
        x: 4420,
        y: floorY - 32,
        w: 460,
        h: 32,
        dps: 2.62,
      },
      {
        kind: "hazard",
        x: 4540,
        y: 248,
        w: 108,
        h: 208,
        dps: 2.54,
      },
      { kind: "solid", x: 4500, y: 332, w: 640, h: 26 },
      {
        kind: "hazard",
        x: 4700,
        y: 282,
        w: 54,
        h: 174,
        dps: 2.5,
      },
      {
        kind: "hazard",
        x: 5060,
        y: floorY - 32,
        w: 400,
        h: 32,
        dps: 2.62,
      },
      { kind: "solid", x: 5140, y: 332, w: 820, h: 26 },
      {
        kind: "hazard",
        x: 4780,
        y: 286,
        w: 50,
        h: 170,
        dps: 2.46,
      },
      {
        kind: "hazard",
        x: 5380,
        y: floorY - 32,
        w: 430,
        h: 32,
        dps: 2.62,
      },
      { kind: "solid", x: 5420, y: 328, w: 1200, h: 26 },
      {
        kind: "patrol",
        id: "chapter_drone_h",
        x: 4820,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -84,
        patrolLeft: 4580,
        patrolRight: 5220,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "chapter_drone_i",
        x: 5380,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 72,
        patrolLeft: 4940,
        patrolRight: 5700,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "chapter_drone_j",
        x: 5940,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -66,
        patrolLeft: 5180,
        patrolRight: 6100,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 5980, y: 236, w: 310, h: 18 },
      {
        kind: "hazard",
        x: 6160,
        y: floorY - 50,
        w: 420,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 6420, y: 286, w: 260, h: 18 },

      {
        kind: "boss_gate",
        x: 7920,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Chapter is the first turn—running head, folio break, section ladder.\nPager stacks the leaf where the rubricator opened the line.",
      },

      { kind: "solid", x: 7988, y: 146, w: 2040, h: 28 },
      { kind: "solid", x: 8042, y: 344, w: 74, h: 144 },
      { kind: "solid", x: 9520, y: 344, w: 74, h: 144 },
      {
        kind: "hazard",
        x: 8120,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.42,
      },
      { kind: "solid", x: 8196, y: floorY - 12, w: 66, h: 12 },
      {
        kind: "hazard",
        x: 8262,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.42,
      },
      { kind: "solid", x: 8338, y: 268, w: 460, h: 22 },
      {
        kind: "hazard",
        x: 8800,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 8868, y: floorY - 11, w: 56, h: 11 },
      {
        kind: "hazard",
        x: 8924,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 8992, y: 384, w: 520, h: 22 },
      { kind: "solid", x: 9300, y: 316, w: 460, h: 20 },
      {
        kind: "exit",
        x: 9960,
        y: 194,
        w: 48,
        h: 86,
      },
    ],
  };
}
