import type { LevelDef } from "./types";

/**
 * Folio XXX — epigraph (front-matter quotation). Ten patrols in **3 + 4 + 3**: macro verb is
 * **pull quote band** (wide emphasis strip like a block quotation), **attribution rail**
 * (offset stepped read for the citation line), then **dash lead** (em-dash corridor before the seal).
 * Still ten drones.
 */
export function createFolioEpigraphPageLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 10200;

  return {
    id: "folio_xxx_epigraph",
    name: "Epigraph — Folio XXX",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      {
        kind: "hazard",
        x: 22,
        y: floorY - 34,
        w: 136,
        h: 34,
        dps: 2.4,
      },
      { kind: "solid", x: 198, y: 390, w: 92, h: 14 },

      /* Volume A — pull quote band */
      {
        kind: "hazard",
        x: 480,
        y: floorY - 34,
        w: 960,
        h: 34,
        dps: 2.58,
      },
      {
        kind: "hazard",
        x: 520,
        y: 188,
        w: 880,
        h: 30,
        dps: 2.48,
      },
      {
        kind: "hazard",
        x: 560,
        y: 248,
        w: 800,
        h: 28,
        dps: 2.46,
      },
      {
        kind: "hazard",
        x: 440,
        y: 132,
        w: 52,
        h: 300,
        dps: 2.5,
      },
      {
        kind: "hazard",
        x: 1340,
        y: 132,
        w: 52,
        h: 300,
        dps: 2.5,
      },
      { kind: "solid", x: 600, y: 334, w: 640, h: 26 },
      {
        kind: "patrol",
        id: "epigraph_drone_a",
        x: 760,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -90,
        patrolLeft: 500,
        patrolRight: 1220,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "epigraph_drone_b",
        x: 1080,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 82,
        patrolLeft: 540,
        patrolRight: 1360,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "epigraph_drone_c",
        x: 1420,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -76,
        patrolLeft: 580,
        patrolRight: 1620,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 1700,
        y: floorY - 36,
        w: 170,
        h: 36,
        dps: 2.68,
      },
      { kind: "solid", x: 1680, y: 346, w: 58, h: 14 },
      { kind: "solid", x: 1810, y: 346, w: 58, h: 14 },

      /* Volume B — attribution rail */
      {
        kind: "hazard",
        x: 1900,
        y: floorY - 32,
        w: 120,
        h: 32,
        dps: 2.54,
      },
      {
        kind: "hazard",
        x: 2080,
        y: 168,
        w: 200,
        h: 28,
        dps: 2.48,
      },
      {
        kind: "hazard",
        x: 2340,
        y: floorY - 30,
        w: 400,
        h: 30,
        dps: 2.58,
      },
      { kind: "solid", x: 2120, y: 330, w: 700, h: 26 },
      {
        kind: "hazard",
        x: 2600,
        y: 224,
        w: 48,
        h: 216,
        dps: 2.5,
      },
      {
        kind: "patrol",
        id: "epigraph_drone_d",
        x: 2260,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 94,
        patrolLeft: 1940,
        patrolRight: 2700,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "epigraph_drone_e",
        x: 2800,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -84,
        patrolLeft: 2180,
        patrolRight: 3140,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "hazard",
        x: 2980,
        y: floorY - 32,
        w: 460,
        h: 32,
        dps: 2.6,
      },
      { kind: "solid", x: 2900, y: 332, w: 780, h: 26 },
      {
        kind: "patrol",
        id: "epigraph_drone_f",
        x: 3360,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 78,
        patrolLeft: 2740,
        patrolRight: 3600,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "hazard",
        x: 3420,
        y: 212,
        w: 52,
        h: 236,
        dps: 2.48,
      },
      {
        kind: "patrol",
        id: "epigraph_drone_g",
        x: 3880,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -72,
        patrolLeft: 3060,
        patrolRight: 4160,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 4120,
        y: floorY - 34,
        w: 210,
        h: 34,
        dps: 2.64,
      },
      { kind: "solid", x: 4140, y: 154, w: 330, h: 16 },
      {
        kind: "checkpoint",
        id: "epigraph_mid",
        x: 4320,
        y: 146,
        w: 48,
        h: 76,
      },

      /* Volume C — dash lead */
      {
        kind: "hazard",
        x: 4400,
        y: floorY - 32,
        w: 440,
        h: 32,
        dps: 2.62,
      },
      {
        kind: "hazard",
        x: 4520,
        y: 246,
        w: 108,
        h: 210,
        dps: 2.54,
      },
      { kind: "solid", x: 4480, y: 332, w: 620, h: 26 },
      {
        kind: "hazard",
        x: 4680,
        y: 280,
        w: 54,
        h: 176,
        dps: 2.5,
      },
      {
        kind: "hazard",
        x: 5040,
        y: floorY - 32,
        w: 380,
        h: 32,
        dps: 2.62,
      },
      { kind: "solid", x: 5120, y: 332, w: 800, h: 26 },
      {
        kind: "hazard",
        x: 4760,
        y: 284,
        w: 50,
        h: 172,
        dps: 2.46,
      },
      {
        kind: "hazard",
        x: 5360,
        y: floorY - 32,
        w: 420,
        h: 32,
        dps: 2.62,
      },
      { kind: "solid", x: 5400, y: 328, w: 1180, h: 26 },
      {
        kind: "patrol",
        id: "epigraph_drone_h",
        x: 4800,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -86,
        patrolLeft: 4560,
        patrolRight: 5200,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "epigraph_drone_i",
        x: 5360,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 74,
        patrolLeft: 4920,
        patrolRight: 5680,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "epigraph_drone_j",
        x: 5920,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -68,
        patrolLeft: 5160,
        patrolRight: 6080,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 5960, y: 236, w: 310, h: 18 },
      {
        kind: "hazard",
        x: 6140,
        y: floorY - 50,
        w: 420,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 6400, y: 286, w: 260, h: 18 },

      {
        kind: "boss_gate",
        x: 7440,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Epigraph is the citation—quote, rail, dash.\nCiter binds what dedication vowed and patron witnessed.",
      },

      { kind: "solid", x: 7508, y: 146, w: 2040, h: 28 },
      { kind: "solid", x: 7562, y: 344, w: 74, h: 144 },
      { kind: "solid", x: 9040, y: 344, w: 74, h: 144 },
      {
        kind: "hazard",
        x: 7640,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.42,
      },
      { kind: "solid", x: 7716, y: floorY - 12, w: 66, h: 12 },
      {
        kind: "hazard",
        x: 7782,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.42,
      },
      { kind: "solid", x: 7858, y: 268, w: 460, h: 22 },
      {
        kind: "hazard",
        x: 8320,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 8388, y: floorY - 11, w: 56, h: 11 },
      {
        kind: "hazard",
        x: 8444,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 8512, y: 384, w: 520, h: 22 },
      { kind: "solid", x: 8820, y: 316, w: 460, h: 20 },
      {
        kind: "exit",
        x: 9480,
        y: 194,
        w: 48,
        h: 86,
      },
    ],
  };
}
