import type { LevelDef } from "./types";

/**
 * Folio XVIII — colophon. Ten patrols in **3 + 4 + 3**: macro verb is **mirror imprint** (paired
 * hazards bias you to center), **curtain bands** (staggered vertical columns weave timing), then a
 * **seal channel** (narrow committed lane). End-of-book pressure without an eleventh drone.
 */
export function createFolioColophonLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 7640;

  return {
    id: "folio_xviii_colophon",
    name: "Colophon — Folio XVIII",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      /* Imprint — symmetric ceiling bites */
      {
        kind: "hazard",
        x: 80,
        y: 210,
        w: 160,
        h: 200,
        dps: 2.38,
      },
      {
        kind: "hazard",
        x: 360,
        y: 210,
        w: 160,
        h: 200,
        dps: 2.38,
      },
      { kind: "solid", x: 260, y: 396, w: 96, h: 16 },
      {
        kind: "hazard",
        x: 560,
        y: floorY - 38,
        w: 200,
        h: 38,
        dps: 2.48,
      },
      {
        kind: "hazard",
        x: 800,
        y: floorY - 38,
        w: 200,
        h: 38,
        dps: 2.48,
      },

      /* Volume A — three floor drones on mirrored runway */
      { kind: "solid", x: 440, y: 332, w: 1520, h: 26 },
      {
        kind: "hazard",
        x: 520,
        y: 230,
        w: 36,
        h: 190,
        dps: 2.52,
      },
      {
        kind: "hazard",
        x: 1840,
        y: 230,
        w: 36,
        h: 190,
        dps: 2.52,
      },
      {
        kind: "patrol",
        id: "colophon_drone_a",
        x: 720,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -100,
        patrolLeft: 460,
        patrolRight: 1180,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "colophon_drone_b",
        x: 1180,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 92,
        patrolLeft: 500,
        patrolRight: 1380,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "colophon_drone_c",
        x: 1640,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -78,
        patrolLeft: 560,
        patrolRight: 1920,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 1980,
        y: floorY - 36,
        w: 120,
        h: 36,
        dps: 2.74,
      },
      { kind: "solid", x: 1960, y: 358, w: 52, h: 14 },
      { kind: "solid", x: 2068, y: 358, w: 52, h: 14 },

      /* Volume B — curtain bands (stagger columns) + four drones */
      {
        kind: "hazard",
        x: 2120,
        y: 260,
        w: 44,
        h: 220,
        dps: 2.5,
      },
      {
        kind: "hazard",
        x: 2280,
        y: 220,
        w: 44,
        h: 240,
        dps: 2.52,
      },
      {
        kind: "hazard",
        x: 2460,
        y: 280,
        w: 44,
        h: 200,
        dps: 2.48,
      },
      {
        kind: "hazard",
        x: 2640,
        y: 200,
        w: 44,
        h: 250,
        dps: 2.54,
      },
      { kind: "solid", x: 2140, y: 332, w: 1180, h: 26 },
      {
        kind: "patrol",
        id: "colophon_drone_d",
        x: 2240,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 106,
        patrolLeft: 2160,
        patrolRight: 2520,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "colophon_drone_e",
        x: 2580,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -88,
        patrolLeft: 2200,
        patrolRight: 2760,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "colophon_drone_f",
        x: 2920,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 74,
        patrolLeft: 2680,
        patrolRight: 3120,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "colophon_drone_g",
        x: 3180,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -82,
        patrolLeft: 2720,
        patrolRight: 3280,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 3340,
        y: floorY - 32,
        w: 200,
        h: 32,
        dps: 2.66,
      },
      { kind: "solid", x: 3360, y: 188, w: 240, h: 16 },
      {
        kind: "checkpoint",
        id: "colophon_mid",
        x: 3440,
        y: 178,
        w: 48,
        h: 76,
      },

      /* Volume C — seal channel (narrow lane) */
      {
        kind: "hazard",
        x: 3520,
        y: 300,
        w: 120,
        h: 180,
        dps: 2.46,
      },
      {
        kind: "hazard",
        x: 4120,
        y: 300,
        w: 120,
        h: 180,
        dps: 2.46,
      },
      { kind: "solid", x: 3660, y: 332, w: 440, h: 24 },
      {
        kind: "hazard",
        x: 3680,
        y: floorY - 44,
        w: 100,
        h: 44,
        dps: 2.58,
      },
      {
        kind: "hazard",
        x: 3980,
        y: floorY - 44,
        w: 100,
        h: 44,
        dps: 2.58,
      },
      {
        kind: "patrol",
        id: "colophon_drone_h",
        x: 3780,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -96,
        patrolLeft: 3680,
        patrolRight: 4040,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "colophon_drone_i",
        x: 3960,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 70,
        patrolLeft: 3720,
        patrolRight: 4120,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "colophon_drone_j",
        x: 4140,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -68,
        patrolLeft: 3800,
        patrolRight: 4280,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 4320, y: 256, w: 220, h: 18 },
      {
        kind: "hazard",
        x: 4400,
        y: floorY - 50,
        w: 280,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 4580, y: 300, w: 140, h: 18 },

      {
        kind: "boss_gate",
        x: 4920,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Colophon is the printer’s mark—mirror, curtain, seal.\nCompositor locks the impression the binder could only stitch.",
      },

      { kind: "solid", x: 4988, y: 146, w: 1980, h: 28 },
      { kind: "solid", x: 5042, y: 344, w: 74, h: 144 },
      { kind: "solid", x: 6440, y: 344, w: 74, h: 144 },
      {
        kind: "hazard",
        x: 5120,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.4,
      },
      { kind: "solid", x: 5196, y: floorY - 12, w: 66, h: 12 },
      {
        kind: "hazard",
        x: 5262,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.4,
      },
      { kind: "solid", x: 5338, y: 268, w: 420, h: 22 },
      {
        kind: "hazard",
        x: 5800,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 5868, y: floorY - 11, w: 56, h: 11 },
      {
        kind: "hazard",
        x: 5924,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.58,
      },
      { kind: "solid", x: 5992, y: 384, w: 480, h: 22 },
      { kind: "solid", x: 6300, y: 316, w: 340, h: 20 },
      {
        kind: "exit",
        x: 6720,
        y: 194,
        w: 48,
        h: 86,
      },
    ],
  };
}
