import type { LevelDef } from "./types";

/**
 * Folio IX — echo line. Unlocks after horizon; exit sealed until the custodian falls.
 */
export function createFolioEchoLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 4680;

  return {
    id: "folio_ix_echo",
    name: "Echo Line — Folio IX",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      { kind: "solid", x: 24, y: 424, w: 136, h: 18 },
      { kind: "solid", x: 210, y: 364, w: 190, h: 18 },
      {
        kind: "hazard",
        x: 160,
        y: floorY - 48,
        w: 270,
        h: 48,
        dps: 2.24,
      },
      { kind: "solid", x: 420, y: 304, w: 148, h: 17 },
      {
        kind: "hazard",
        x: 580,
        y: floorY - 42,
        w: 330,
        h: 42,
        dps: 2.38,
      },
      { kind: "solid", x: 560, y: 388, w: 46, h: 92 },

      /* Seven drones */
      { kind: "solid", x: 620, y: 338, w: 1040, h: 26 },
      {
        kind: "patrol",
        id: "echo_drone_a",
        x: 840,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -112,
        patrolLeft: 660,
        patrolRight: 1580,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "echo_drone_b",
        x: 1320,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 102,
        patrolLeft: 680,
        patrolRight: 1540,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "echo_drone_c",
        x: 1100,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -88,
        patrolLeft: 720,
        patrolRight: 1480,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "echo_drone_d",
        x: 760,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 80,
        patrolLeft: 740,
        patrolRight: 1420,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "echo_drone_e",
        x: 1240,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -74,
        patrolLeft: 780,
        patrolRight: 1380,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "echo_drone_f",
        x: 940,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 66,
        patrolLeft: 800,
        patrolRight: 1340,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "echo_drone_g",
        x: 1460,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -58,
        patrolLeft: 900,
        patrolRight: 1520,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 1700, y: 264, w: 168, h: 18 },
      {
        kind: "hazard",
        x: 1760,
        y: floorY - 46,
        w: 210,
        h: 46,
        dps: 2.52,
      },
      { kind: "solid", x: 1940, y: 204, w: 250, h: 18 },

      {
        kind: "checkpoint",
        id: "echo_mid",
        x: 2020,
        y: 194,
        w: 48,
        h: 76,
      },

      { kind: "solid", x: 2160, y: 308, w: 320, h: 22 },
      {
        kind: "hazard",
        x: 2280,
        y: floorY - 40,
        w: 170,
        h: 40,
        dps: 2.42,
      },
      { kind: "solid", x: 2480, y: 248, w: 150, h: 16 },
      {
        kind: "hazard",
        x: 2620,
        y: floorY - 36,
        w: 130,
        h: 36,
        dps: 2.4,
      },

      {
        kind: "boss_gate",
        x: 2968,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Echo doesn’t repeat—it insists.\nCustodian counts every footfall twice before the line releases.",
      },

      { kind: "solid", x: 3036, y: 162, w: 1400, h: 28 },
      { kind: "solid", x: 3090, y: 360, w: 62, h: 120 },
      { kind: "solid", x: 4320, y: 360, w: 62, h: 120 },
      {
        kind: "hazard",
        x: 3160,
        y: floorY - 40,
        w: 66,
        h: 40,
        dps: 2.3,
      },
      { kind: "solid", x: 3226, y: floorY - 12, w: 54, h: 12 },
      {
        kind: "hazard",
        x: 3280,
        y: floorY - 40,
        w: 66,
        h: 40,
        dps: 2.3,
      },
      { kind: "solid", x: 3346, y: 284, w: 300, h: 22 },
      {
        kind: "hazard",
        x: 3660,
        y: floorY - 38,
        w: 58,
        h: 38,
        dps: 2.46,
      },
      { kind: "solid", x: 3718, y: floorY - 11, w: 46, h: 11 },
      {
        kind: "hazard",
        x: 3764,
        y: floorY - 38,
        w: 58,
        h: 38,
        dps: 2.46,
      },
      { kind: "solid", x: 3822, y: 400, w: 360, h: 22 },
      { kind: "solid", x: 4040, y: 332, w: 220, h: 20 },
      {
        kind: "exit",
        x: 4340,
        y: 210,
        w: 48,
        h: 86,
      },
    ],
  };
}
