import type { LevelDef } from "./types";

/**
 * Folio XXIX — dedication. Ten patrols in **3 + 4 + 3**: macro verb is **center well**
 * (symmetrical margin hazards framing a narrow sacred runway), **ornament brackets**
 * (corner flourishes + diagonal bites), then **vow strip** (commitment teeth before the seal).
 * Still ten drones.
 */
export function createFolioDedicationLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 10080;

  return {
    id: "folio_xxix_dedication",
    name: "Dedication — Folio XXIX",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      {
        kind: "hazard",
        x: 22,
        y: floorY - 34,
        w: 136,
        h: 34,
        dps: 2.4,
      },
      { kind: "solid", x: 198, y: 390, w: 92, h: 14 },

      /* Volume A — center well */
      {
        kind: "hazard",
        x: 460,
        y: 152,
        w: 46,
        h: 312,
        dps: 2.52,
      },
      {
        kind: "hazard",
        x: 1220,
        y: 152,
        w: 46,
        h: 312,
        dps: 2.52,
      },
      {
        kind: "hazard",
        x: 560,
        y: floorY - 34,
        w: 600,
        h: 34,
        dps: 2.58,
      },
      {
        kind: "hazard",
        x: 600,
        y: 196,
        w: 520,
        h: 28,
        dps: 2.46,
      },
      { kind: "solid", x: 620, y: 336, w: 520, h: 26 },
      {
        kind: "patrol",
        id: "dedication_drone_a",
        x: 780,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -92,
        patrolLeft: 500,
        patrolRight: 1180,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "dedication_drone_b",
        x: 1040,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 84,
        patrolLeft: 540,
        patrolRight: 1320,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "dedication_drone_c",
        x: 1380,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -78,
        patrolLeft: 580,
        patrolRight: 1580,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 1680,
        y: floorY - 36,
        w: 170,
        h: 36,
        dps: 2.68,
      },
      { kind: "solid", x: 1660, y: 346, w: 58, h: 14 },
      { kind: "solid", x: 1790, y: 346, w: 58, h: 14 },

      /* Volume B — ornament brackets */
      {
        kind: "hazard",
        x: 1880,
        y: floorY - 32,
        w: 120,
        h: 32,
        dps: 2.54,
      },
      {
        kind: "hazard",
        x: 2060,
        y: 176,
        w: 180,
        h: 28,
        dps: 2.48,
      },
      {
        kind: "hazard",
        x: 2320,
        y: floorY - 30,
        w: 380,
        h: 30,
        dps: 2.58,
      },
      { kind: "solid", x: 2100, y: 330, w: 680, h: 26 },
      {
        kind: "hazard",
        x: 2580,
        y: 220,
        w: 48,
        h: 220,
        dps: 2.5,
      },
      {
        kind: "patrol",
        id: "dedication_drone_d",
        x: 2240,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 96,
        patrolLeft: 1920,
        patrolRight: 2680,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "dedication_drone_e",
        x: 2780,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -86,
        patrolLeft: 2160,
        patrolRight: 3120,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "hazard",
        x: 2960,
        y: floorY - 32,
        w: 440,
        h: 32,
        dps: 2.6,
      },
      { kind: "solid", x: 2880, y: 332, w: 760, h: 26 },
      {
        kind: "patrol",
        id: "dedication_drone_f",
        x: 3320,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 80,
        patrolLeft: 2720,
        patrolRight: 3560,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "hazard",
        x: 3400,
        y: 208,
        w: 52,
        h: 240,
        dps: 2.48,
      },
      {
        kind: "patrol",
        id: "dedication_drone_g",
        x: 3840,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -74,
        patrolLeft: 3040,
        patrolRight: 4120,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 4080,
        y: floorY - 34,
        w: 210,
        h: 34,
        dps: 2.64,
      },
      { kind: "solid", x: 4100, y: 154, w: 330, h: 16 },
      {
        kind: "checkpoint",
        id: "dedication_mid",
        x: 4280,
        y: 146,
        w: 48,
        h: 76,
      },

      /* Volume C — vow strip */
      {
        kind: "hazard",
        x: 4360,
        y: floorY - 32,
        w: 420,
        h: 32,
        dps: 2.62,
      },
      {
        kind: "hazard",
        x: 4480,
        y: 244,
        w: 108,
        h: 212,
        dps: 2.54,
      },
      { kind: "solid", x: 4440, y: 332, w: 600, h: 26 },
      {
        kind: "hazard",
        x: 4640,
        y: 278,
        w: 54,
        h: 178,
        dps: 2.5,
      },
      {
        kind: "hazard",
        x: 5000,
        y: floorY - 32,
        w: 360,
        h: 32,
        dps: 2.62,
      },
      { kind: "solid", x: 5080, y: 332, w: 780, h: 26 },
      {
        kind: "hazard",
        x: 4720,
        y: 282,
        w: 50,
        h: 174,
        dps: 2.46,
      },
      {
        kind: "hazard",
        x: 5320,
        y: floorY - 32,
        w: 400,
        h: 32,
        dps: 2.62,
      },
      { kind: "solid", x: 5360, y: 328, w: 1140, h: 26 },
      {
        kind: "patrol",
        id: "dedication_drone_h",
        x: 4760,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -88,
        patrolLeft: 4520,
        patrolRight: 5160,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "dedication_drone_i",
        x: 5320,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 76,
        patrolLeft: 4880,
        patrolRight: 5640,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "dedication_drone_j",
        x: 5880,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -70,
        patrolLeft: 5120,
        patrolRight: 6040,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 5920, y: 236, w: 310, h: 18 },
      {
        kind: "hazard",
        x: 6100,
        y: floorY - 50,
        w: 420,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 6360, y: 286, w: 260, h: 18 },

      {
        kind: "boss_gate",
        x: 7360,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Dedication is the vow—well, brackets, strip.\nPatron witnesses what copyright filed and registrar stamped.",
      },

      { kind: "solid", x: 7428, y: 146, w: 2040, h: 28 },
      { kind: "solid", x: 7482, y: 344, w: 74, h: 144 },
      { kind: "solid", x: 8960, y: 344, w: 74, h: 144 },
      {
        kind: "hazard",
        x: 7560,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.42,
      },
      { kind: "solid", x: 7636, y: floorY - 12, w: 66, h: 12 },
      {
        kind: "hazard",
        x: 7702,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.42,
      },
      { kind: "solid", x: 7778, y: 268, w: 460, h: 22 },
      {
        kind: "hazard",
        x: 8240,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 8308, y: floorY - 11, w: 56, h: 11 },
      {
        kind: "hazard",
        x: 8364,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 8432, y: 384, w: 520, h: 22 },
      { kind: "solid", x: 8740, y: 316, w: 460, h: 20 },
      {
        kind: "exit",
        x: 9400,
        y: 194,
        w: 48,
        h: 86,
      },
    ],
  };
}
