import type { LevelDef } from "./types";

/**
 * Folio XXVII — title page. Ten patrols in **3 + 4 + 3**: macro verb is **masthead lift** (top and
 * bottom hazard bars framing a tall central runway), **byline tread** (sequential floor teeth like
 * a credit line), then **imprint block** (dense corner cluster before the seal). Still ten drones.
 */
export function createFolioTitlepageLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 9840;

  return {
    id: "folio_xxvii_titlepage",
    name: "Title page — Folio XXVII",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      {
        kind: "hazard",
        x: 18,
        y: floorY - 32,
        w: 144,
        h: 32,
        dps: 2.4,
      },
      { kind: "solid", x: 188, y: 390, w: 100, h: 14 },

      /* Volume A — masthead lift */
      {
        kind: "hazard",
        x: 460,
        y: 188,
        w: 1000,
        h: 30,
        dps: 2.46,
      },
      {
        kind: "hazard",
        x: 500,
        y: floorY - 36,
        w: 920,
        h: 36,
        dps: 2.52,
      },
      {
        kind: "hazard",
        x: 520,
        y: 256,
        w: 48,
        h: 200,
        dps: 2.5,
      },
      {
        kind: "hazard",
        x: 1420,
        y: 260,
        w: 48,
        h: 196,
        dps: 2.5,
      },
      { kind: "solid", x: 580, y: 332, w: 840, h: 26 },
      {
        kind: "patrol",
        id: "titlepage_drone_a",
        x: 780,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -96,
        patrolLeft: 480,
        patrolRight: 1340,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "titlepage_drone_b",
        x: 1260,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 88,
        patrolLeft: 520,
        patrolRight: 1760,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "titlepage_drone_c",
        x: 1640,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -82,
        patrolLeft: 560,
        patrolRight: 1840,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 1900,
        y: floorY - 36,
        w: 140,
        h: 36,
        dps: 2.7,
      },
      { kind: "solid", x: 1880, y: 346, w: 52, h: 14 },
      { kind: "solid", x: 1988, y: 346, w: 52, h: 14 },

      /* Volume B — byline tread */
      {
        kind: "hazard",
        x: 2040,
        y: floorY - 30,
        w: 100,
        h: 30,
        dps: 2.52,
      },
      {
        kind: "hazard",
        x: 2220,
        y: floorY - 30,
        w: 100,
        h: 30,
        dps: 2.52,
      },
      {
        kind: "hazard",
        x: 2400,
        y: floorY - 30,
        w: 100,
        h: 30,
        dps: 2.52,
      },
      {
        kind: "hazard",
        x: 2580,
        y: floorY - 30,
        w: 100,
        h: 30,
        dps: 2.52,
      },
      { kind: "solid", x: 2080, y: 332, w: 720, h: 26 },
      {
        kind: "hazard",
        x: 2760,
        y: floorY - 30,
        w: 100,
        h: 30,
        dps: 2.52,
      },
      {
        kind: "hazard",
        x: 2940,
        y: floorY - 30,
        w: 100,
        h: 30,
        dps: 2.52,
      },
      {
        kind: "hazard",
        x: 3120,
        y: floorY - 30,
        w: 100,
        h: 30,
        dps: 2.52,
      },
      {
        kind: "hazard",
        x: 3300,
        y: floorY - 30,
        w: 100,
        h: 30,
        dps: 2.52,
      },
      { kind: "solid", x: 2480, y: 328, w: 1040, h: 26 },
      {
        kind: "patrol",
        id: "titlepage_drone_d",
        x: 2240,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 104,
        patrolLeft: 2000,
        patrolRight: 2720,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "titlepage_drone_e",
        x: 2860,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -92,
        patrolLeft: 2460,
        patrolRight: 3260,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "titlepage_drone_f",
        x: 3400,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 86,
        patrolLeft: 2980,
        patrolRight: 3760,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "titlepage_drone_g",
        x: 3920,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -98,
        patrolLeft: 3280,
        patrolRight: 4340,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 4120,
        y: floorY - 34,
        w: 220,
        h: 34,
        dps: 2.64,
      },
      { kind: "solid", x: 4140, y: 156, w: 340, h: 16 },
      {
        kind: "checkpoint",
        id: "titlepage_mid",
        x: 4240,
        y: 146,
        w: 48,
        h: 76,
      },

      /* Volume C — imprint block */
      {
        kind: "hazard",
        x: 4320,
        y: 236,
        w: 120,
        h: 220,
        dps: 2.54,
      },
      {
        kind: "hazard",
        x: 4480,
        y: floorY - 34,
        w: 380,
        h: 34,
        dps: 2.62,
      },
      { kind: "solid", x: 4360, y: 332, w: 560, h: 26 },
      {
        kind: "hazard",
        x: 4520,
        y: 272,
        w: 56,
        h: 184,
        dps: 2.5,
      },
      {
        kind: "hazard",
        x: 4880,
        y: floorY - 32,
        w: 360,
        h: 32,
        dps: 2.62,
      },
      { kind: "solid", x: 5020, y: 332, w: 740, h: 26 },
      {
        kind: "hazard",
        x: 4600,
        y: 280,
        w: 52,
        h: 176,
        dps: 2.48,
      },
      {
        kind: "hazard",
        x: 5240,
        y: floorY - 32,
        w: 340,
        h: 32,
        dps: 2.62,
      },
      { kind: "solid", x: 5380, y: 328, w: 700, h: 26 },
      {
        kind: "hazard",
        x: 4680,
        y: 284,
        w: 50,
        h: 172,
        dps: 2.46,
      },
      {
        kind: "hazard",
        x: 5580,
        y: floorY - 32,
        w: 380,
        h: 32,
        dps: 2.62,
      },
      { kind: "solid", x: 5280, y: 332, w: 1240, h: 26 },
      {
        kind: "patrol",
        id: "titlepage_drone_h",
        x: 4720,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -90,
        patrolLeft: 4460,
        patrolRight: 5120,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "titlepage_drone_i",
        x: 5280,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 80,
        patrolLeft: 4760,
        patrolRight: 5640,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "titlepage_drone_j",
        x: 5800,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -74,
        patrolLeft: 5000,
        patrolRight: 5960,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 5840, y: 236, w: 320, h: 18 },
      {
        kind: "hazard",
        x: 6000,
        y: floorY - 50,
        w: 420,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 6260, y: 286, w: 260, h: 18 },

      {
        kind: "boss_gate",
        x: 7200,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Title page is the imprint—masthead, byline, block.\nImprinter presses what frontispiece engraved and engraver cut.",
      },

      { kind: "solid", x: 7268, y: 146, w: 2040, h: 28 },
      { kind: "solid", x: 7322, y: 344, w: 74, h: 144 },
      { kind: "solid", x: 8800, y: 344, w: 74, h: 144 },
      {
        kind: "hazard",
        x: 7400,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.42,
      },
      { kind: "solid", x: 7476, y: floorY - 12, w: 66, h: 12 },
      {
        kind: "hazard",
        x: 7542,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.42,
      },
      { kind: "solid", x: 7618, y: 268, w: 460, h: 22 },
      {
        kind: "hazard",
        x: 8080,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 8148, y: floorY - 11, w: 56, h: 11 },
      {
        kind: "hazard",
        x: 8204,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 8272, y: 384, w: 520, h: 22 },
      { kind: "solid", x: 8580, y: 316, w: 460, h: 20 },
      {
        kind: "exit",
        x: 9240,
        y: 194,
        w: 48,
        h: 86,
      },
    ],
  };
}
