import type { LevelDef } from "./types";

/**
 * Folio XIII — coda. Same drone *count* as XII (10): difficulty shifts to route-reading,
 * trench pressure, and a busier arena — not an eleventh patrol body.
 */
export function createFolioCodaLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 6400;

  return {
    id: "folio_xiii_coda",
    name: "Coda — Folio XIII",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      { kind: "solid", x: 14, y: 432, w: 118, h: 18 },
      { kind: "solid", x: 160, y: 372, w: 168, h: 18 },
      {
        kind: "hazard",
        x: 110,
        y: floorY - 56,
        w: 310,
        h: 56,
        dps: 2.34,
      },
      /* Stepping read — forces a deliberate line over pain */
      {
        kind: "hazard",
        x: 260,
        y: floorY - 36,
        w: 420,
        h: 36,
        dps: 2.62,
      },
      { kind: "solid", x: 300, y: 402, w: 56, h: 16 },
      { kind: "solid", x: 410, y: 348, w: 52, h: 16 },
      { kind: "solid", x: 520, y: 296, w: 58, h: 16 },

      { kind: "solid", x: 640, y: 312, w: 128, h: 17 },
      {
        kind: "hazard",
        x: 780,
        y: floorY - 50,
        w: 340,
        h: 50,
        dps: 2.48,
      },
      { kind: "solid", x: 760, y: 396, w: 54, h: 84 },

      /* First drone cluster (5) */
      { kind: "solid", x: 820, y: 332, w: 720, h: 26 },
      {
        kind: "patrol",
        id: "coda_drone_a",
        x: 1020,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -118,
        patrolLeft: 850,
        patrolRight: 1500,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "coda_drone_b",
        x: 1380,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 104,
        patrolLeft: 870,
        patrolRight: 1460,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "coda_drone_c",
        x: 1180,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -90,
        patrolLeft: 900,
        patrolRight: 1420,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "coda_drone_d",
        x: 920,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 86,
        patrolLeft: 920,
        patrolRight: 1380,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "coda_drone_e",
        x: 1280,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -78,
        patrolLeft: 960,
        patrolRight: 1340,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      /* Trench — high DPS; side lip is the honest read */
      {
        kind: "hazard",
        x: 1520,
        y: floorY - 28,
        w: 220,
        h: 28,
        dps: 2.78,
      },
      { kind: "solid", x: 1500, y: 360, w: 44, h: 14 },
      { kind: "solid", x: 1740, y: 360, w: 44, h: 14 },

      /* Second drone cluster (5) */
      { kind: "solid", x: 1820, y: 332, w: 780, h: 26 },
      {
        kind: "patrol",
        id: "coda_drone_f",
        x: 2040,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 112,
        patrolLeft: 1860,
        patrolRight: 2540,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "coda_drone_g",
        x: 2380,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -100,
        patrolLeft: 1880,
        patrolRight: 2500,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "coda_drone_h",
        x: 2180,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 82,
        patrolLeft: 1920,
        patrolRight: 2460,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "coda_drone_i",
        x: 1920,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -70,
        patrolLeft: 1960,
        patrolRight: 2420,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "coda_drone_j",
        x: 2280,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 58,
        patrolLeft: 2000,
        patrolRight: 2380,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 2640, y: 252, w: 200, h: 18 },
      {
        kind: "hazard",
        x: 2700,
        y: floorY - 54,
        w: 250,
        h: 54,
        dps: 2.6,
      },
      { kind: "solid", x: 2880, y: 192, w: 290, h: 18 },

      {
        kind: "checkpoint",
        id: "coda_mid",
        x: 2960,
        y: 182,
        w: 48,
        h: 76,
      },

      { kind: "solid", x: 3100, y: 296, w: 400, h: 22 },
      {
        kind: "hazard",
        x: 3220,
        y: floorY - 48,
        w: 210,
        h: 48,
        dps: 2.52,
      },
      { kind: "solid", x: 3420, y: 236, w: 178, h: 16 },
      {
        kind: "hazard",
        x: 3560,
        y: floorY - 44,
        w: 160,
        h: 44,
        dps: 2.5,
      },

      {
        kind: "boss_gate",
        x: 3940,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Coda isn’t extra pages—it’s the margin where ink bleeds.\nCurator shelves what you survived; prove it belongs there.",
      },

      { kind: "solid", x: 4008, y: 150, w: 1860, h: 28 },
      { kind: "solid", x: 4062, y: 348, w: 70, h: 136 },
      { kind: "solid", x: 5744, y: 348, w: 70, h: 136 },
      /* Busier arena floor reads — four pips instead of a simple pair */
      {
        kind: "hazard",
        x: 4140,
        y: floorY - 48,
        w: 72,
        h: 48,
        dps: 2.4,
      },
      { kind: "solid", x: 4212, y: floorY - 12, w: 62, h: 12 },
      {
        kind: "hazard",
        x: 4284,
        y: floorY - 48,
        w: 72,
        h: 48,
        dps: 2.4,
      },
      {
        kind: "hazard",
        x: 4720,
        y: floorY - 40,
        w: 64,
        h: 40,
        dps: 2.55,
      },
      { kind: "solid", x: 4784, y: floorY - 11, w: 52, h: 11 },
      {
        kind: "hazard",
        x: 4836,
        y: floorY - 40,
        w: 64,
        h: 40,
        dps: 2.55,
      },
      { kind: "solid", x: 4900, y: 272, w: 380, h: 22 },
      {
        kind: "hazard",
        x: 5280,
        y: floorY - 46,
        w: 68,
        h: 46,
        dps: 2.54,
      },
      { kind: "solid", x: 5348, y: floorY - 11, w: 54, h: 11 },
      {
        kind: "hazard",
        x: 5402,
        y: floorY - 46,
        w: 68,
        h: 46,
        dps: 2.54,
      },
      { kind: "solid", x: 5470, y: 388, w: 440, h: 22 },
      { kind: "solid", x: 5740, y: 320, w: 300, h: 20 },
      {
        kind: "exit",
        x: 6120,
        y: 198,
        w: 48,
        h: 86,
      },
    ],
  };
}
