import type { LevelDef } from "./types";

/**
 * Folio XI — zenith climb. Unlocks after verge; exit sealed until the exarch falls.
 */
export function createFolioZenithLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 5580;

  return {
    id: "folio_xi_zenith",
    name: "Zenith — Folio XI",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      { kind: "solid", x: 18, y: 428, w: 128, h: 18 },
      { kind: "solid", x: 190, y: 368, w: 180, h: 18 },
      {
        kind: "hazard",
        x: 140,
        y: floorY - 52,
        w: 290,
        h: 52,
        dps: 2.28,
      },
      { kind: "solid", x: 380, y: 308, w: 138, h: 17 },
      {
        kind: "hazard",
        x: 540,
        y: floorY - 46,
        w: 350,
        h: 46,
        dps: 2.42,
      },
      { kind: "solid", x: 520, y: 392, w: 50, h: 88 },

      /* Nine drones */
      { kind: "solid", x: 560, y: 334, w: 1280, h: 26 },
      {
        kind: "patrol",
        id: "zenith_drone_a",
        x: 800,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -118,
        patrolLeft: 590,
        patrolRight: 1780,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "zenith_drone_b",
        x: 1460,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 108,
        patrolLeft: 610,
        patrolRight: 1740,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "zenith_drone_c",
        x: 1200,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -94,
        patrolLeft: 650,
        patrolRight: 1680,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "zenith_drone_d",
        x: 720,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 86,
        patrolLeft: 670,
        patrolRight: 1620,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "zenith_drone_e",
        x: 1360,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -80,
        patrolLeft: 710,
        patrolRight: 1580,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "zenith_drone_f",
        x: 900,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 72,
        patrolLeft: 730,
        patrolRight: 1540,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "zenith_drone_g",
        x: 1600,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -66,
        patrolLeft: 900,
        patrolRight: 1700,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "zenith_drone_h",
        x: 1060,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 58,
        patrolLeft: 780,
        patrolRight: 1500,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "zenith_drone_i",
        x: 1280,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -52,
        patrolLeft: 950,
        patrolRight: 1660,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 1880, y: 256, w: 184, h: 18 },
      {
        kind: "hazard",
        x: 1940,
        y: floorY - 50,
        w: 230,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 2120, y: 196, w: 270, h: 18 },

      {
        kind: "checkpoint",
        id: "zenith_mid",
        x: 2200,
        y: 186,
        w: 48,
        h: 76,
      },

      { kind: "solid", x: 2340, y: 300, w: 360, h: 22 },
      {
        kind: "hazard",
        x: 2460,
        y: floorY - 44,
        w: 190,
        h: 44,
        dps: 2.46,
      },
      { kind: "solid", x: 2660, y: 240, w: 165, h: 16 },
      {
        kind: "hazard",
        x: 2800,
        y: floorY - 40,
        w: 145,
        h: 40,
        dps: 2.44,
      },

      {
        kind: "boss_gate",
        x: 3180,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Zenith isn’t height—it’s verdict.\nExarch won’t stamp the arc complete until you justify the climb.",
      },

      { kind: "solid", x: 3248, y: 154, w: 1560, h: 28 },
      { kind: "solid", x: 3302, y: 352, w: 66, h: 128 },
      { kind: "solid", x: 4688, y: 352, w: 66, h: 128 },
      {
        kind: "hazard",
        x: 3370,
        y: floorY - 44,
        w: 70,
        h: 44,
        dps: 2.34,
      },
      { kind: "solid", x: 3440, y: floorY - 12, w: 58, h: 12 },
      {
        kind: "hazard",
        x: 3498,
        y: floorY - 44,
        w: 70,
        h: 44,
        dps: 2.34,
      },
      { kind: "solid", x: 3568, y: 276, w: 340, h: 22 },
      {
        kind: "hazard",
        x: 3920,
        y: floorY - 42,
        w: 62,
        h: 42,
        dps: 2.5,
      },
      { kind: "solid", x: 3982, y: floorY - 11, w: 50, h: 11 },
      {
        kind: "hazard",
        x: 4032,
        y: floorY - 42,
        w: 62,
        h: 42,
        dps: 2.5,
      },
      { kind: "solid", x: 4094, y: 392, w: 400, h: 22 },
      { kind: "solid", x: 4340, y: 324, w: 260, h: 20 },
      {
        kind: "exit",
        x: 4700,
        y: 202,
        w: 48,
        h: 86,
      },
    ],
  };
}
