import type { LevelDef } from "./types";

/**
 * Folio VIII — horizon strip. Unlocks after exile; exit sealed until the sovereign falls.
 */
export function createFolioHorizonLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 4200;

  return {
    id: "folio_viii_horizon",
    name: "Horizon — Folio VIII",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      { kind: "solid", x: 28, y: 420, w: 140, h: 18 },
      { kind: "solid", x: 220, y: 360, w: 200, h: 18 },
      {
        kind: "hazard",
        x: 170,
        y: floorY - 46,
        w: 260,
        h: 46,
        dps: 2.2,
      },
      { kind: "solid", x: 440, y: 300, w: 150, h: 17 },
      {
        kind: "hazard",
        x: 600,
        y: floorY - 40,
        w: 320,
        h: 40,
        dps: 2.36,
      },
      { kind: "solid", x: 580, y: 384, w: 44, h: 96 },

      /* Six drones */
      { kind: "solid", x: 660, y: 340, w: 860, h: 26 },
      {
        kind: "patrol",
        id: "horizon_drone_a",
        x: 880,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -108,
        patrolLeft: 700,
        patrolRight: 1480,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "horizon_drone_b",
        x: 1280,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 98,
        patrolLeft: 720,
        patrolRight: 1440,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "horizon_drone_c",
        x: 1060,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -84,
        patrolLeft: 760,
        patrolRight: 1380,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "horizon_drone_d",
        x: 800,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 76,
        patrolLeft: 780,
        patrolRight: 1340,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "horizon_drone_e",
        x: 1180,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -70,
        patrolLeft: 820,
        patrolRight: 1300,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "horizon_drone_f",
        x: 980,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 62,
        patrolLeft: 860,
        patrolRight: 1260,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 1540, y: 268, w: 160, h: 18 },
      {
        kind: "hazard",
        x: 1600,
        y: floorY - 44,
        w: 200,
        h: 44,
        dps: 2.5,
      },
      { kind: "solid", x: 1780, y: 208, w: 240, h: 18 },

      {
        kind: "checkpoint",
        id: "horizon_mid",
        x: 1860,
        y: 198,
        w: 48,
        h: 76,
      },

      { kind: "solid", x: 2000, y: 312, w: 300, h: 22 },
      {
        kind: "hazard",
        x: 2120,
        y: floorY - 38,
        w: 160,
        h: 38,
        dps: 2.4,
      },
      { kind: "solid", x: 2320, y: 252, w: 140, h: 16 },
      {
        kind: "hazard",
        x: 2460,
        y: floorY - 34,
        w: 120,
        h: 34,
        dps: 2.38,
      },

      {
        kind: "boss_gate",
        x: 2688,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "The horizon isn’t empty—it’s waiting.\nSovereign won’t let the strip end until you earn the view.",
      },

      { kind: "solid", x: 2756, y: 168, w: 1180, h: 28 },
      { kind: "solid", x: 2810, y: 364, w: 60, h: 116 },
      { kind: "solid", x: 3820, y: 364, w: 60, h: 116 },
      {
        kind: "hazard",
        x: 2880,
        y: floorY - 38,
        w: 64,
        h: 38,
        dps: 2.28,
      },
      { kind: "solid", x: 2944, y: floorY - 12, w: 52, h: 12 },
      {
        kind: "hazard",
        x: 2996,
        y: floorY - 38,
        w: 64,
        h: 38,
        dps: 2.28,
      },
      { kind: "solid", x: 3060, y: 288, w: 280, h: 22 },
      {
        kind: "hazard",
        x: 3360,
        y: floorY - 36,
        w: 56,
        h: 36,
        dps: 2.44,
      },
      { kind: "solid", x: 3416, y: floorY - 11, w: 44, h: 11 },
      {
        kind: "hazard",
        x: 3460,
        y: floorY - 36,
        w: 56,
        h: 36,
        dps: 2.44,
      },
      { kind: "solid", x: 3516, y: 404, w: 340, h: 22 },
      { kind: "solid", x: 3720, y: 336, w: 200, h: 20 },
      {
        kind: "exit",
        x: 3860,
        y: 214,
        w: 48,
        h: 86,
      },
    ],
  };
}
