import type { LevelDef } from "./types";

/**
 * Folio X — verge. Unlocks after echo; exit sealed until the harbinger falls.
 */
export function createFolioVergeLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 5040;

  return {
    id: "folio_x_verge",
    name: "Verge — Folio X",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      { kind: "solid", x: 20, y: 426, w: 132, h: 18 },
      { kind: "solid", x: 200, y: 366, w: 184, h: 18 },
      {
        kind: "hazard",
        x: 150,
        y: floorY - 50,
        w: 280,
        h: 50,
        dps: 2.26,
      },
      { kind: "solid", x: 400, y: 306, w: 142, h: 17 },
      {
        kind: "hazard",
        x: 560,
        y: floorY - 44,
        w: 340,
        h: 44,
        dps: 2.4,
      },
      { kind: "solid", x: 540, y: 390, w: 48, h: 90 },

      /* Eight drones */
      { kind: "solid", x: 590, y: 336, w: 1120, h: 26 },
      {
        kind: "patrol",
        id: "verge_drone_a",
        x: 820,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -116,
        patrolLeft: 620,
        patrolRight: 1660,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "verge_drone_b",
        x: 1380,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 106,
        patrolLeft: 640,
        patrolRight: 1620,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "verge_drone_c",
        x: 1140,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -92,
        patrolLeft: 680,
        patrolRight: 1560,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "verge_drone_d",
        x: 740,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 84,
        patrolLeft: 700,
        patrolRight: 1500,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "verge_drone_e",
        x: 1280,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -78,
        patrolLeft: 740,
        patrolRight: 1460,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "verge_drone_f",
        x: 920,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 70,
        patrolLeft: 760,
        patrolRight: 1420,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "verge_drone_g",
        x: 1520,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -62,
        patrolLeft: 880,
        patrolRight: 1580,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "verge_drone_h",
        x: 1040,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 54,
        patrolLeft: 820,
        patrolRight: 1380,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 1760, y: 260, w: 176, h: 18 },
      {
        kind: "hazard",
        x: 1820,
        y: floorY - 48,
        w: 220,
        h: 48,
        dps: 2.54,
      },
      { kind: "solid", x: 2000, y: 200, w: 260, h: 18 },

      {
        kind: "checkpoint",
        id: "verge_mid",
        x: 2080,
        y: 190,
        w: 48,
        h: 76,
      },

      { kind: "solid", x: 2220, y: 304, w: 340, h: 22 },
      {
        kind: "hazard",
        x: 2340,
        y: floorY - 42,
        w: 180,
        h: 42,
        dps: 2.44,
      },
      { kind: "solid", x: 2540, y: 244, w: 158, h: 16 },
      {
        kind: "hazard",
        x: 2680,
        y: floorY - 38,
        w: 138,
        h: 38,
        dps: 2.42,
      },

      {
        kind: "boss_gate",
        x: 3048,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Verge is where the city admits it’s thin.\nHarbinger stands where the echo ends—earn the drop.",
      },

      { kind: "solid", x: 3116, y: 158, w: 1480, h: 28 },
      { kind: "solid", x: 3170, y: 356, w: 64, h: 124 },
      { kind: "solid", x: 4478, y: 356, w: 64, h: 124 },
      {
        kind: "hazard",
        x: 3240,
        y: floorY - 42,
        w: 68,
        h: 42,
        dps: 2.32,
      },
      { kind: "solid", x: 3308, y: floorY - 12, w: 56, h: 12 },
      {
        kind: "hazard",
        x: 3364,
        y: floorY - 42,
        w: 68,
        h: 42,
        dps: 2.32,
      },
      { kind: "solid", x: 3432, y: 280, w: 320, h: 22 },
      {
        kind: "hazard",
        x: 3760,
        y: floorY - 40,
        w: 60,
        h: 40,
        dps: 2.48,
      },
      { kind: "solid", x: 3820, y: floorY - 11, w: 48, h: 11 },
      {
        kind: "hazard",
        x: 3868,
        y: floorY - 40,
        w: 60,
        h: 40,
        dps: 2.48,
      },
      { kind: "solid", x: 3928, y: 396, w: 380, h: 22 },
      { kind: "solid", x: 4160, y: 328, w: 240, h: 20 },
      {
        kind: "exit",
        x: 4480,
        y: 206,
        w: 48,
        h: 86,
      },
    ],
  };
}
