import type { LevelDef } from "./types";

/**
 * Folio XXXVII — interlude (breath between chapters). Ten patrols in **3 + 4 + 3**:
 * macro verb is **bleed trim** (edge hazard pulls you off margin), **signature stitch**
 * (paired hazards threading the midline), then **gather fold** (tiers compressing toward the gate).
 */

export function createFolioInterludeLevel(): LevelDef {
  const floorY = 480;
  const floorH = 120;
  const W = 11000;

  return {
    id: "folio_xxxvii_interlude",
    name: "Interlude — Folio XXXVII",
    width: W,
    height: 600,
    entities: [
      { kind: "solid", x: 0, y: floorY, w: W, h: floorH },

      {
        kind: "hazard",
        x: 102,
        y: floorY - 34,
        w: 136,
        h: 34,
        dps: 2.4,
      },
      { kind: "solid", x: 278, y: 390, w: 92, h: 14 },

      /* Volume A — bleed trim */
      {
        kind: "hazard",
        x: 480,
        y: 140,
        w: 72,
        h: 320,
        dps: 2.54,
      },
      {
        kind: "hazard",
        x: 580,
        y: floorY - 34,
        w: 720,
        h: 34,
        dps: 2.58,
      },
      {
        kind: "hazard",
        x: 600,
        y: 176,
        w: 640,
        h: 30,
        dps: 2.48,
      },
      {
        kind: "hazard",
        x: 640,
        y: 236,
        w: 560,
        h: 28,
        dps: 2.46,
      },
      {
        kind: "hazard",
        x: 1320,
        y: 188,
        w: 48,
        h: 272,
        dps: 2.52,
      },
      { kind: "solid", x: 660, y: 334, w: 680, h: 26 },
      {
        kind: "patrol",
        id: "interlude_drone_a",
        x: 880,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -88,
        patrolLeft: 560,
        patrolRight: 1360,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "interlude_drone_b",
        x: 1180,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 80,
        patrolLeft: 600,
        patrolRight: 1460,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "interlude_drone_c",
        x: 1560,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -74,
        patrolLeft: 640,
        patrolRight: 1760,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 1820,
        y: floorY - 36,
        w: 180,
        h: 36,
        dps: 2.68,
      },
      { kind: "solid", x: 1800, y: 346, w: 58, h: 14 },
      { kind: "solid", x: 1930, y: 346, w: 58, h: 14 },

      /* Volume B — signature stitch */
      {
        kind: "hazard",
        x: 2000,
        y: floorY - 32,
        w: 128,
        h: 32,
        dps: 2.54,
      },
      {
        kind: "hazard",
        x: 2180,
        y: 172,
        w: 190,
        h: 28,
        dps: 2.48,
      },
      {
        kind: "hazard",
        x: 2440,
        y: floorY - 30,
        w: 400,
        h: 30,
        dps: 2.58,
      },
      { kind: "solid", x: 2220, y: 330, w: 700, h: 26 },
      {
        kind: "hazard",
        x: 2700,
        y: 226,
        w: 48,
        h: 214,
        dps: 2.5,
      },
      {
        kind: "patrol",
        id: "interlude_drone_d",
        x: 2360,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 92,
        patrolLeft: 2040,
        patrolRight: 2800,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "interlude_drone_e",
        x: 2900,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -82,
        patrolLeft: 2280,
        patrolRight: 3240,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "hazard",
        x: 3080,
        y: floorY - 32,
        w: 470,
        h: 32,
        dps: 2.6,
      },
      { kind: "solid", x: 3000, y: 332, w: 800, h: 26 },
      {
        kind: "patrol",
        id: "interlude_drone_f",
        x: 3460,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 76,
        patrolLeft: 2840,
        patrolRight: 3700,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "hazard",
        x: 3520,
        y: 214,
        w: 52,
        h: 234,
        dps: 2.48,
      },
      {
        kind: "patrol",
        id: "interlude_drone_g",
        x: 3980,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -70,
        patrolLeft: 3160,
        patrolRight: 4260,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      {
        kind: "hazard",
        x: 4220,
        y: floorY - 34,
        w: 210,
        h: 34,
        dps: 2.64,
      },
      { kind: "solid", x: 4240, y: 154, w: 330, h: 16 },
      {
        kind: "checkpoint",
        id: "interlude_mid",
        x: 4420,
        y: 146,
        w: 48,
        h: 76,
      },

      /* Volume C — gather fold */
      {
        kind: "hazard",
        x: 4500,
        y: floorY - 32,
        w: 460,
        h: 32,
        dps: 2.62,
      },
      {
        kind: "hazard",
        x: 4620,
        y: 248,
        w: 108,
        h: 208,
        dps: 2.54,
      },
      { kind: "solid", x: 4580, y: 332, w: 640, h: 26 },
      {
        kind: "hazard",
        x: 4780,
        y: 282,
        w: 54,
        h: 174,
        dps: 2.5,
      },
      {
        kind: "hazard",
        x: 5140,
        y: floorY - 32,
        w: 400,
        h: 32,
        dps: 2.62,
      },
      { kind: "solid", x: 5220, y: 332, w: 820, h: 26 },
      {
        kind: "hazard",
        x: 4860,
        y: 286,
        w: 50,
        h: 170,
        dps: 2.46,
      },
      {
        kind: "hazard",
        x: 5460,
        y: floorY - 32,
        w: 430,
        h: 32,
        dps: 2.62,
      },
      { kind: "solid", x: 5500, y: 328, w: 1200, h: 26 },
      {
        kind: "patrol",
        id: "interlude_drone_h",
        x: 4900,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -84,
        patrolLeft: 4660,
        patrolRight: 5300,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "interlude_drone_i",
        x: 5460,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: 72,
        patrolLeft: 5020,
        patrolRight: 5780,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },
      {
        kind: "patrol",
        id: "interlude_drone_j",
        x: 6020,
        y: floorY - 30,
        w: 28,
        h: 28,
        vx: -66,
        patrolLeft: 5260,
        patrolRight: 6180,
        hp: 1,
        damage: 1,
        isMiniboss: false,
        hurtCooldownMs: 0,
      },

      { kind: "solid", x: 6060, y: 236, w: 310, h: 18 },
      {
        kind: "hazard",
        x: 6240,
        y: floorY - 50,
        w: 420,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 6500, y: 286, w: 260, h: 18 },

      {
        kind: "boss_gate",
        x: 8000,
        y: 0,
        w: 44,
        h: 520,
        enterLine:
          "Interlude is the breath—bleed trim, signature stitch, gather fold.\nIntervenor minds the gap where the pager turned the leaf.",
      },

      { kind: "solid", x: 8068, y: 146, w: 2040, h: 28 },
      { kind: "solid", x: 8122, y: 344, w: 74, h: 144 },
      { kind: "solid", x: 9600, y: 344, w: 74, h: 144 },
      {
        kind: "hazard",
        x: 8200,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.42,
      },
      { kind: "solid", x: 8276, y: floorY - 12, w: 66, h: 12 },
      {
        kind: "hazard",
        x: 8342,
        y: floorY - 52,
        w: 76,
        h: 52,
        dps: 2.42,
      },
      { kind: "solid", x: 8418, y: 268, w: 460, h: 22 },
      {
        kind: "hazard",
        x: 8880,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 8948, y: floorY - 11, w: 56, h: 11 },
      {
        kind: "hazard",
        x: 9004,
        y: floorY - 50,
        w: 68,
        h: 50,
        dps: 2.56,
      },
      { kind: "solid", x: 9072, y: 384, w: 520, h: 22 },
      { kind: "solid", x: 9380, y: 316, w: 460, h: 20 },
      {
        kind: "exit",
        x: 10040,
        y: 194,
        w: 48,
        h: 86,
      },
    ],
  };
}
